# Generated by Django 4.2.29 on 2026-05-11 07:34

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0005_region_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('chem_code', models.IntegerField(unique=True, verbose_name='Chemical Code')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('cas_number', models.CharField(blank=True, max_length=32, verbose_name='CAS Number')),
                ('dtxsid', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='DTXSID')),
                ('iarc_group', models.CharField(blank=True, choices=[('1', 'Group 1 – Carcinogenic to humans'), ('2A', 'Group 2A – Probably carcinogenic to humans'), ('2B', 'Group 2B – Possibly carcinogenic to humans'), ('3', 'Group 3 – Not classifiable as to carcinogenicity')], max_length=2, verbose_name='IARC Group')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('biopesticide', 'Biopesticide'), ('carcinogen', 'Carcinogen'), ('cholinesterase_inhibitor', 'Cholinesterase Inhibitor'), ('developmental_toxin', 'Developmental Toxin'), ('fumigant', 'Fumigant'), ('groundwater_contaminant', 'Groundwater Contaminant'), ('oil', 'Oil'), ('reproductive_toxin', 'Reproductive Toxin'), ('toxic_air_contaminant', 'Toxic Air Contaminant')], max_length=32), blank=True, default=list, size=None, verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'pesticides.Chemical',
                'verbose_name_plural': 'Chemicals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('site_code', models.CharField(max_length=8, unique=True, verbose_name='Site Code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'pesticides.Commodity',
                'verbose_name_plural': 'Commodities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('prodno', models.IntegerField(unique=True, verbose_name='Product Number')),
                ('reg_number', models.CharField(max_length=64, unique=True, verbose_name='Registration Number')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('fumigant', models.BooleanField(default=False, verbose_name='Fumigant')),
                ('california_restricted', models.BooleanField(default=False, verbose_name='California Restricted')),
            ],
            options={
                'verbose_name': 'pesticides.Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_active', models.FloatField(blank=True, null=True, verbose_name='Percent Active')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_chemicals', to='pesticides.chemical')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_chemicals', to='pesticides.product')),
            ],
            options={
                'unique_together': {('product', 'chemical')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='chemicals',
            field=models.ManyToManyField(related_name='products', through='pesticides.ProductChemical', to='pesticides.chemical', verbose_name='Chemicals'),
        ),
        migrations.CreateModel(
            name='PesticideNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('application_id', models.IntegerField(unique=True, verbose_name='Application ID')),
                ('comtr', models.CharField(db_index=True, max_length=11, verbose_name='COMTR')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point')),
                ('scheduled_application', models.DateTimeField(db_index=True, verbose_name='Scheduled Application')),
                ('treated_amount', models.FloatField(blank=True, null=True, verbose_name='Treated Amount')),
                ('treated_units', models.CharField(blank=True, max_length=32, verbose_name='Treated Units')),
                ('application_method', models.CharField(blank=True, max_length=128, verbose_name='Application Method')),
                ('chemicals', models.ManyToManyField(blank=True, related_name='pesticide_notices', to='pesticides.chemical', verbose_name='Chemicals')),
                ('county', models.ForeignKey(blank=True, limit_choices_to={'type': 'county'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_pesticide_notices', to='regions.region', verbose_name='County')),
                ('mtrs', models.ForeignKey(blank=True, limit_choices_to={'type': 'mtrs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesticide_notices', to='regions.region', verbose_name='MTRS Section')),
                ('products', models.ManyToManyField(blank=True, related_name='pesticide_notices', to='pesticides.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Pesticide Notice',
                'verbose_name_plural': 'Pesticide Notices',
                'ordering': ['scheduled_application'],
            },
        ),
        migrations.CreateModel(
            name='PesticideUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('use_no', models.IntegerField(verbose_name='Use Number')),
                ('comtrs', models.CharField(blank=True, max_length=11, verbose_name='COMTRS')),
                ('site_code', models.CharField(blank=True, max_length=8, verbose_name='Site Code')),
                ('pct_active', models.FloatField(blank=True, null=True, verbose_name='Percent Active')),
                ('lbs_chemical', models.FloatField(blank=True, null=True, verbose_name='Pounds of Chemical Used')),
                ('lbs_product', models.FloatField(blank=True, null=True, verbose_name='Pounds of Product Used')),
                ('amount_product', models.FloatField(blank=True, null=True, verbose_name='Amount of Product Used')),
                ('unit_product', models.CharField(blank=True, max_length=8, verbose_name='Unit of Measure')),
                ('acres_planted', models.FloatField(blank=True, null=True, verbose_name='Acres Planted')),
                ('unit_planted', models.CharField(blank=True, max_length=4, verbose_name='Unit Planted')),
                ('acres_treated', models.FloatField(blank=True, null=True, verbose_name='Acres Treated')),
                ('unit_treated', models.CharField(blank=True, max_length=4, verbose_name='Unit Treated')),
                ('application_count', models.IntegerField(blank=True, null=True, verbose_name='Application Count')),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='Application Date')),
                ('aerial_ground', models.CharField(blank=True, choices=[('A', 'Aerial'), ('F', 'Fumigation'), ('G', 'Ground'), ('O', 'Other')], max_length=1, verbose_name='Aerial/Ground')),
                ('record_id', models.CharField(blank=True, max_length=4, verbose_name='Record ID')),
                ('chemical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pur_records', to='pesticides.chemical', verbose_name='pesticides.Chemical')),
                ('commodity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pur_records', to='pesticides.commodity', verbose_name='pesticides.Commodity')),
                ('county', models.ForeignKey(limit_choices_to={'type': 'county'}, on_delete=django.db.models.deletion.PROTECT, related_name='pur_records', to='regions.region', verbose_name='County')),
                ('mtrs', models.ForeignKey(blank=True, limit_choices_to={'type': 'mtrs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pur_records_mtrs', to='regions.region', verbose_name='MTRS Section')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pur_records', to='pesticides.product', verbose_name='pesticides.Product')),
            ],
            options={
                'verbose_name': 'Pesticide Use',
                'verbose_name_plural': 'Pesticide Uses',
                'indexes': [models.Index(fields=['year', 'county'], name='pesticides__year_5d6f86_idx'), models.Index(fields=['year', 'use_no'], name='pesticides__year_65a2ab_idx'), models.Index(fields=['mtrs'], name='pesticides__mtrs_id_ea67c2_idx'), models.Index(fields=['product'], name='pesticides__product_a3b1c7_idx'), models.Index(fields=['chemical'], name='pesticides__chemica_47bd04_idx'), models.Index(fields=['commodity'], name='pesticides__commodi_23ff82_idx'), models.Index(fields=['application_date'], name='pesticides__applica_a6454e_idx')],
            },
        ),
    ]
