# Generated by Django 4.2.30 on 2026-05-12 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_region_metadata'),
        ('pesticides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesticideuse',
            options={'ordering': ['-application_date', '-year'], 'verbose_name': 'Pesticide Use', 'verbose_name_plural': 'Pesticide Uses'},
        ),
        migrations.AlterField(
            model_name='pesticideuse',
            name='mtrs',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'mtrs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesticide_uses_mtrs', to='regions.region', verbose_name='MTRS Section'),
        ),
    ]
