# Generated by Django 4.2.29 on 2026-05-11 04:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_add_mtrs_region_type'),
        ('pesticides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprayApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('application_id', models.IntegerField(unique=True, verbose_name='Application ID')),
                ('comtr', models.CharField(db_index=True, max_length=11, verbose_name='COMTR')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point')),
                ('scheduled_application', models.DateTimeField(db_index=True, verbose_name='Scheduled Application')),
                ('treated_amount', models.FloatField(blank=True, null=True, verbose_name='Treated Amount')),
                ('treated_units', models.CharField(blank=True, max_length=32, verbose_name='Treated Units')),
                ('application_method', models.CharField(blank=True, max_length=128, verbose_name='Application Method')),
                ('products', models.JSONField(default=list, verbose_name='Products')),
                ('chemicals', models.ManyToManyField(blank=True, related_name='spray_applications', to='pesticides.chemical', verbose_name='Chemicals')),
                ('county', models.ForeignKey(blank=True, limit_choices_to={'type': 'county'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_spray_applications', to='regions.region', verbose_name='County')),
                ('mtrs', models.ForeignKey(blank=True, limit_choices_to={'type': 'mtrs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spray_applications', to='regions.region', verbose_name='MTRS Section')),
            ],
            options={
                'verbose_name': 'Spray Application',
                'verbose_name_plural': 'Spray Applications',
                'ordering': ['scheduled_application'],
            },
        ),
    ]
