# Generated by Django 4.2.29 on 2026-05-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purrecord',
            name='aerial_ground',
            field=models.CharField(blank=True, choices=[('A', 'Aerial'), ('F', 'Fumigation'), ('G', 'Ground'), ('O', 'Other')], max_length=1, verbose_name='Aerial/Ground'),
        ),
    ]
