# Generated by Django 4.2.29 on 2026-05-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='dtxsid',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='DTXSID'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='iarc_group',
            field=models.CharField(blank=True, choices=[('1', 'Group 1 – Carcinogenic to humans'), ('2A', 'Group 2A – Probably carcinogenic to humans'), ('2B', 'Group 2B – Possibly carcinogenic to humans'), ('3', 'Group 3 – Not classifiable as to carcinogenicity')], max_length=2, verbose_name='IARC Group'),
        ),
    ]
