# Generated by Django 5.2.16 on 2026-09-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0002_alter_pesticideuse_options_alter_pesticideuse_mtrs'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pesticideuse',
            index=models.Index(fields=['chemical', 'year'], name='pesticides__chemica_85a287_idx'),
        ),
        migrations.AddIndex(
            model_name='pesticideuse',
            index=models.Index(fields=['product', 'year'], name='pesticides__product_93c98d_idx'),
        ),
        migrations.AddIndex(
            model_name='pesticideuse',
            index=models.Index(fields=['commodity', 'year'], name='pesticides__commodi_798480_idx'),
        ),
    ]
