# Generated by Django 5.2.16 on 2026-09-17 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0003_pesticideuse_fk_year_indexes'),
        ('regions', '0005_region_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesticideUseRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.IntegerField(help_text='1-12, or 0 when the record has no application date', verbose_name='Month')),
                ('lbs_chemical', models.FloatField(default=0, verbose_name='Pounds of Chemical')),
                ('lbs_product', models.FloatField(default=0, verbose_name='Pounds of Product')),
                ('acres_treated', models.FloatField(default=0, verbose_name='Acres Treated')),
                ('applications', models.IntegerField(default=0, verbose_name='Applications')),
                ('chemical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='pesticides.chemical', verbose_name='pesticides.Chemical')),
                ('commodity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='pesticides.commodity', verbose_name='pesticides.Commodity')),
                ('county', models.ForeignKey(limit_choices_to={'type': 'county'}, on_delete=django.db.models.deletion.CASCADE, related_name='pesticide_rollups', to='regions.region', verbose_name='County')),
                ('mtrs', models.ForeignKey(blank=True, limit_choices_to={'type': 'mtrs'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesticide_rollups_mtrs', to='regions.region', verbose_name='MTRS Section')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='pesticides.product', verbose_name='pesticides.Product')),
            ],
            options={
                'verbose_name': 'Pesticide Use Rollup',
                'verbose_name_plural': 'Pesticide Use Rollups',
                'indexes': [models.Index(fields=['year', 'mtrs'], name='pesticides__year_042e38_idx'), models.Index(fields=['year', 'county'], name='pesticides__year_2fee25_idx'), models.Index(fields=['year', 'chemical'], name='pesticides__year_83f2ff_idx'), models.Index(fields=['year', 'product'], name='pesticides__year_9f2172_idx'), models.Index(fields=['year', 'commodity'], name='pesticides__year_4c43cc_idx'), models.Index(fields=['mtrs', 'year', 'month'], name='pesticides__mtrs_id_70b6d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('year', 'month', 'county', 'mtrs', 'chemical', 'product', 'commodity'), name='pesticides_rollup_key', nulls_distinct=False)],
            },
        ),
    ]
