# Generated by Django 5.2.16 on 2026-09-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0004_pesticideuserollup'),
        ('regions', '0005_region_metadata'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pesticideuserollup',
            index=models.Index(fields=['year', 'county', 'chemical'], name='pesticides__year_671957_idx'),
        ),
        migrations.AddIndex(
            model_name='pesticideuserollup',
            index=models.Index(fields=['year', 'county', 'product'], name='pesticides__year_d140bd_idx'),
        ),
        migrations.AddIndex(
            model_name='pesticideuserollup',
            index=models.Index(fields=['year', 'county', 'commodity'], name='pesticides__year_5934dd_idx'),
        ),
    ]
