# Generated by Django 5.2.16 on 2026-09-19 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0005_rollup_county_entity_indexes'),
        ('regions', '0005_region_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesticideUseTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('lbs_chemical', models.FloatField(default=0, verbose_name='Pounds of Chemical')),
                ('lbs_product', models.FloatField(default=0, verbose_name='Pounds of Product')),
                ('acres_treated', models.FloatField(default=0, verbose_name='Acres Treated')),
                ('applications', models.IntegerField(default=0, verbose_name='Applications')),
                ('chemical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='totals', to='pesticides.chemical', verbose_name='pesticides.Chemical')),
                ('commodity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='totals', to='pesticides.commodity', verbose_name='pesticides.Commodity')),
                ('county', models.ForeignKey(limit_choices_to={'type': 'county'}, on_delete=django.db.models.deletion.CASCADE, related_name='pesticide_totals', to='regions.region', verbose_name='County')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='totals', to='pesticides.product', verbose_name='pesticides.Product')),
            ],
            options={
                'verbose_name': 'Pesticide Use Total',
                'verbose_name_plural': 'Pesticide Use Totals',
                'indexes': [models.Index(fields=['year', 'chemical'], name='pesticides__year_365edc_idx'), models.Index(fields=['year', 'product'], name='pesticides__year_5178fa_idx'), models.Index(fields=['year', 'commodity'], name='pesticides__year_7edd2b_idx'), models.Index(fields=['year', 'county'], name='pesticides__year_e45fbb_idx')],
                'constraints': [models.UniqueConstraint(fields=('year', 'county', 'chemical', 'product', 'commodity'), name='pesticides_total_key', nulls_distinct=False), models.CheckConstraint(condition=models.Q(models.Q(('chemical__isnull', False), ('commodity__isnull', True), ('product__isnull', True)), models.Q(('chemical__isnull', True), ('commodity__isnull', True), ('product__isnull', False)), models.Q(('chemical__isnull', True), ('commodity__isnull', False), ('product__isnull', True)), _connector='OR'), name='pesticides_total_one_entity')],
            },
        ),
    ]
