# Generated by Django 5.2.16 on 2026-09-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0006_pesticideusetotal'),
        ('regions', '0005_region_metadata'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pesticideuserollup',
            index=models.Index(fields=['year', 'commodity', 'chemical'], name='pesticides__year_1f6fca_idx'),
        ),
        migrations.AddIndex(
            model_name='pesticideuserollup',
            index=models.Index(fields=['year', 'county', 'commodity', 'chemical'], name='pesticides__year_f55155_idx'),
        ),
    ]
