# Generated by Django 5.2.16 on 2026-09-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0007_rollup_commodity_chemical_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Preferred Name'),
        ),
    ]
