# Generated by Django 5.2.16 on 2026-09-25 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0011_remove_product_california_restricted'),
        ('regions', '0010_remove_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesticideSectionTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('lbs_chemical', models.FloatField(default=0, verbose_name='Pounds of Chemical')),
                ('lbs_product', models.FloatField(default=0, verbose_name='Pounds of Product')),
                ('acres_treated', models.FloatField(default=0, verbose_name='Acres Treated')),
                ('applications', models.IntegerField(default=0, verbose_name='Applications')),
                ('mtrs', models.ForeignKey(limit_choices_to={'type': 'mtrs'}, on_delete=django.db.models.deletion.CASCADE, related_name='pesticide_section_totals', to='regions.region', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Pesticide Section Total',
                'verbose_name_plural': 'Pesticide Section Totals',
                'indexes': [models.Index(fields=['year', 'mtrs'], include=('lbs_chemical', 'lbs_product', 'acres_treated', 'applications'), name='pesticides_section_total_cov')],
                'constraints': [models.UniqueConstraint(fields=('year', 'mtrs'), name='pesticides_section_total_key')],
            },
        ),
    ]
