# Generated by Django 5.2.16 on 2026-09-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0012_pesticidesectiontotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_fumigant',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Fumigant'),
        ),
        # Carry CDPR's flag over at once, so fumigants stay fumigants from the
        # moment of migrate rather than after the full rebuild classifies them.
        migrations.RunSQL(
            'UPDATE pesticides_product SET is_fumigant = fumigant',
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='product',
            name='fumigant',
            field=models.BooleanField(default=False, verbose_name='CDPR fumigant flag'),
        ),
    ]
