# Generated by Django 5.2.16 on 2026-09-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0013_product_is_fumigant'),
        ('regions', '0010_remove_place_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pesticideuserollup',
            name='pesticides_rollup_key',
        ),
        migrations.AddField(
            model_name='pesticideuserollup',
            name='method',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Application method'),
        ),
        migrations.AddConstraint(
            model_name='pesticideuserollup',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'county', 'mtrs', 'chemical', 'product', 'commodity', 'method'), name='pesticides_rollup_key', nulls_distinct=False),
        ),
    ]
