# Generated by Django 5.2.16 on 2026-09-29 16:48

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0014_pesticideuserollup_method'),
        ('regions', '0010_remove_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FumigationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.IntegerField(unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Fumigation Method',
                'verbose_name_plural': 'Fumigation Methods',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pesticideuse',
            name='fume_method',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uses', to='pesticides.fumigationmethod', verbose_name='Fumigation Method'),
        ),
    ]
