# Generated by Django 5.2.16 on 2026-09-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0016_pesticideuse_fume_method_idx'),
        ('regions', '0010_remove_place_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pesticidesectiontotal',
            name='pesticides_section_total_cov',
        ),
        migrations.AddField(
            model_name='pesticidesectiontotal',
            name='acres_once',
            field=models.FloatField(default=0, verbose_name='Acres Treated, once per record'),
        ),
        migrations.AddField(
            model_name='pesticidesectiontotal',
            name='lbs_product_once',
            field=models.FloatField(default=0, verbose_name='Pounds of Product, once per record'),
        ),
        migrations.AddField(
            model_name='pesticidesectiontotal',
            name='records',
            field=models.IntegerField(default=0, verbose_name='Records'),
        ),
        migrations.AddField(
            model_name='pesticideuserollup',
            name='acres_once',
            field=models.FloatField(default=0, verbose_name='Acres Treated, once per record'),
        ),
        migrations.AddField(
            model_name='pesticideuserollup',
            name='lbs_product_once',
            field=models.FloatField(default=0, verbose_name='Pounds of Product, once per record'),
        ),
        migrations.AddField(
            model_name='pesticideuserollup',
            name='records',
            field=models.IntegerField(default=0, verbose_name='Records'),
        ),
        migrations.AddField(
            model_name='pesticideusetotal',
            name='acres_once',
            field=models.FloatField(default=0, verbose_name='Acres Treated, once per record'),
        ),
        migrations.AddField(
            model_name='pesticideusetotal',
            name='lbs_product_once',
            field=models.FloatField(default=0, verbose_name='Pounds of Product, once per record'),
        ),
        migrations.AddField(
            model_name='pesticideusetotal',
            name='records',
            field=models.IntegerField(default=0, verbose_name='Records'),
        ),
        migrations.AddIndex(
            model_name='pesticidesectiontotal',
            index=models.Index(fields=['year', 'mtrs'], include=('lbs_chemical', 'lbs_product', 'acres_treated', 'applications', 'records', 'lbs_product_once', 'acres_once'), name='pesticides_section_total_cov'),
        ),
    ]
