# Generated by Django 5.2.16 on 2026-10-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0017_rollup_records_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='california_restricted',
            field=models.BooleanField(default=None, null=True, verbose_name='California restricted'),
        ),
        migrations.AddField(
            model_name='product',
            name='federally_restricted',
            field=models.BooleanField(default=None, null=True, verbose_name='Federally restricted'),
        ),
    ]
