# Generated by Django 2.2.9 on 2020-05-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
