# Generated by Django 2.2.9 on 2020-05-20 09:21

import django.contrib.postgres.indexes

from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0002_auto_20200520_0802'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='purple_entr_data_16cdcc_gin'),
        ),
    ]
