# Generated by Django 3.0.6 on 2020-06-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0003_auto_20200520_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purpleair',
            name='latest',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='PurpleAir',
        ),
    ]
