# Generated by Django 5.2.15 on 2026-06-13 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0036_host_monitor_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='VOZBox',
            fields=[
                ('monitor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitors.monitor')),
                ('sensor_id', models.CharField(max_length=64, unique=True, verbose_name='sensor ID')),
            ],
            options={
                'verbose_name': 'VOZbox',
            },
            bases=('monitors.monitor',),
        ),
    ]
