# Generated by Django 5.2.15 on 2026-07-12 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0036_host_monitor_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIMIS',
            fields=[
                ('monitor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitors.monitor')),
                ('station_number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'CIMIS',
            },
            bases=('monitors.monitor',),
        ),
    ]
