x-build-base: &build-base
  build:
    context: .
    target: base
  volumes:
    - .:/app
  env_file:
    - .env
  depends_on:
    db:
      condition: service_healthy
    queue:
      condition: service_healthy
    cache:
      condition: service_healthy

services:
  db:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_DB: sjvair
      POSTGRES_USER: sjvair
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sjvair"]
      interval: 5s
      timeout: 3s
      retries: 10

  queue:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  cache:
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
    healthcheck:
      test: ["CMD", "pidof", "memcached"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    <<: *build-base
    build:
      context: .
      target: web
    command: python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    profiles: ["default", "web"]

  worker-primary:
    <<: *build-base
    command: python manage.py djangohuey --simple --queue primary
    profiles: ["default", "workers"]

  worker-secondary:
    <<: *build-base
    command: python manage.py djangohuey --simple --queue secondary
    profiles: ["workers"]

  test:
    <<: *build-base
    build:
      context: .
      target: test
    command: pytest
    env_file:
      - .env.test
    depends_on:
      db:
        condition: service_healthy
    profiles: ["test"]

volumes:
  pgdata:
