
services:
  db:
    image: docker.io/postgis/postgis:17-3.5
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sjvair
      POSTGRES_USER: sjvair
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: docker.io/library/redis:8
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  memcached:
    image: docker.io/library/memcached:1.6
    container_name: memcached
    restart: unless-stopped
    ports:
      - "11211:11211"

  web:
    build: .
    container_name: web
    command: wait-for-services.sh python manage.py runserver 0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - memcached
      - redis
    profiles: ["web"]

  huey-primary:
    build: .
    container_name: huey-primary
    command: wait-for-services.sh python manage.py djangohuey --simple --queue primary
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - memcached
      - redis
    profiles: ["queue"]

  huey-secondary:
    build: .
    container_name: huey-secondary
    command: wait-for-services.sh python manage.py djangohuey --simple --queue secondary
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - memcached
      - redis
    profiles: ["queue"]

  test:
    build: .
    command: pytest
    volumes:
      - .:/app
    env_file:
      - .env.test
    depends_on:
      - db
      - redis
      - memcached
    profiles: ["test"]

volumes:
  pgdata:
