# Generated by Django 3.2.5 on 2021-08-11 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_smalluuid.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0017_auto_20210312_1234'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pm25_average', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('level', models.CharField(choices=[('unhealthy_sensitive', 'Unhealthy for Sensitive Groups'), ('unhealthy', 'Unhealthy'), ('very_unhealthy', 'Very Unhealthy'), ('hazardous', 'Hazardous')], max_length=25)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitors.monitor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
