# Generated by Django 4.2.20 on 2025-06-10 23:35

import camp.apps.entries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='user_subscriptions',
        ),
        migrations.AddField(
            model_name='subscription',
            name='entry_type',
            field=camp.apps.entries.fields.EntryTypeField(default='pm25', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='level',
            field=models.CharField(max_length=25),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'monitor', 'entry_type'), name='user_subscriptions'),
        ),
    ]
