# Generated by Django 4.2.20 on 2025-06-24 16:06

import camp.apps.entries.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='entry_type',
            field=camp.apps.entries.fields.EntryTypeField(default='pm25', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='level',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='AlertUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('timestamp', models.DateTimeField()),
                ('level', models.CharField(max_length=25)),
                ('average', models.DecimalField(decimal_places=2, max_digits=8)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='alerts.alert')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
