# Generated by Django 4.2.20 on 2025-07-07 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_remove_alert_level_remove_alert_pm25_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='latest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alertupdate'),
        ),
    ]
