# Generated by Django 5.2.16 on 2026-10-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alert_alertupdate_sqids'),
        ('monitors', '0037_remove_county_choices'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('end_time__isnull', True)), fields=('monitor', 'entry_type'), name='one_open_alert_per_monitor_entry_type'),
        ),
    ]
