# Generated by Django 5.2.16 on 2026-10-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alert_one_open_per_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('alert', 'Alert'), ('reminder', 'Reminder')], default='alert', max_length=10, verbose_name='Kind'),
        ),
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.CharField(blank=True, max_length=25, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='below_threshold_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Below threshold since'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last notified at'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_notified_level',
            field=models.CharField(blank=True, max_length=25, verbose_name='Last notified level'),
        ),
    ]
