# Generated by Django 5.2.16 on 2026-10-07 23:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_sms_alerts_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('provider_id', ''), _negated=True), fields=['provider_id'], name='notification_provider_id_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['subscription', 'created'], name='notification_sub_created_idx'),
        ),
    ]
