# Generated by Django 2.2.4 on 2019-08-22 20:10

import camp.utils.validators
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models
import resticus.encoders


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('location', models.CharField(choices=[('inside', 'inside'), ('outside', 'outside')], max_length=10)),
                ('altitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('location', models.CharField(choices=[('inside', 'inside'), ('outside', 'outside')], max_length=10)),
                ('altitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=resticus.encoders.JSONEncoder, validators=[camp.utils.validators.JSONSchemaValidator({'properties': {'celcius': {'type': 'number'}, 'humidity': {'type': 'number'}, 'pm2': {'properties': {'a': {'properties': {'particles_03um': {'type': 'number'}, 'particles_05um': {'type': 'number'}, 'particles_100um': {'type': 'number'}, 'particles_10um': {'type': 'number'}, 'particles_25um': {'type': 'number'}, 'particles_50um': {'type': 'number'}, 'pm100_env': {'type': 'number'}, 'pm100_standard': {'type': 'number'}, 'pm10_env': {'type': 'number'}, 'pm10_standard': {'type': 'number'}, 'pm25_env': {'type': 'number'}, 'pm25_standard': {'type': 'number'}}, 'required': ['pm10_standard', 'pm25_standard', 'pm100_standard', 'pm10_env', 'pm25_env', 'pm100_env', 'particles_03um', 'particles_05um', 'particles_10um', 'particles_25um', 'particles_50um', 'particles_100um'], 'type': 'object'}, 'b': {'properties': {'particles_03um': {'type': 'number'}, 'particles_05um': {'type': 'number'}, 'particles_100um': {'type': 'number'}, 'particles_10um': {'type': 'number'}, 'particles_25um': {'type': 'number'}, 'particles_50um': {'type': 'number'}, 'pm100_env': {'type': 'number'}, 'pm100_standard': {'type': 'number'}, 'pm10_env': {'type': 'number'}, 'pm10_standard': {'type': 'number'}, 'pm25_env': {'type': 'number'}, 'pm25_standard': {'type': 'number'}}, 'required': ['pm10_standard', 'pm25_standard', 'pm100_standard', 'pm10_env', 'pm25_env', 'pm100_env', 'particles_03um', 'particles_05um', 'particles_10um', 'particles_25um', 'particles_50um', 'particles_100um'], 'type': 'object'}}, 'required': ['a', 'b'], 'type': 'object'}, 'pressure': {'type': 'number'}, 'voc': {'type': 'number'}}, 'required': ['celcius', 'humidity', 'pressure', 'voc', 'pm2'], 'type': 'object'})])),
                ('is_processed', models.BooleanField(default=False)),
                ('celcius', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('fahrenheit', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pm2_a', django.contrib.postgres.fields.jsonb.JSONField(encoder=resticus.encoders.JSONEncoder, null=True, validators=[camp.utils.validators.JSONSchemaValidator({'properties': {'particles_03um': {'type': 'number'}, 'particles_05um': {'type': 'number'}, 'particles_100um': {'type': 'number'}, 'particles_10um': {'type': 'number'}, 'particles_25um': {'type': 'number'}, 'particles_50um': {'type': 'number'}, 'pm100_env': {'type': 'number'}, 'pm100_standard': {'type': 'number'}, 'pm10_env': {'type': 'number'}, 'pm10_standard': {'type': 'number'}, 'pm25_env': {'type': 'number'}, 'pm25_standard': {'type': 'number'}}, 'required': ['pm10_standard', 'pm25_standard', 'pm100_standard', 'pm10_env', 'pm25_env', 'pm100_env', 'particles_03um', 'particles_05um', 'particles_10um', 'particles_25um', 'particles_50um', 'particles_100um'], 'type': 'object'})])),
                ('pm2_b', django.contrib.postgres.fields.jsonb.JSONField(encoder=resticus.encoders.JSONEncoder, null=True, validators=[camp.utils.validators.JSONSchemaValidator({'properties': {'particles_03um': {'type': 'number'}, 'particles_05um': {'type': 'number'}, 'particles_100um': {'type': 'number'}, 'particles_10um': {'type': 'number'}, 'particles_25um': {'type': 'number'}, 'particles_50um': {'type': 'number'}, 'pm100_env': {'type': 'number'}, 'pm100_standard': {'type': 'number'}, 'pm10_env': {'type': 'number'}, 'pm10_standard': {'type': 'number'}, 'pm25_env': {'type': 'number'}, 'pm25_standard': {'type': 'number'}}, 'required': ['pm10_standard', 'pm25_standard', 'pm100_standard', 'pm10_env', 'pm25_env', 'pm100_env', 'particles_03um', 'particles_05um', 'particles_10um', 'particles_25um', 'particles_50um', 'particles_100um'], 'type': 'object'})])),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='sensors.Sensor')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='latest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_latest', to='sensors.SensorData'),
        ),
    ]
