# Generated by Django 2.2.4 on 2019-08-28 21:49

import camp.utils.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import resticus.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='altitude',
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=resticus.encoders.JSONEncoder, validators=[camp.utils.validators.JSONSchemaValidator({'properties': {'celcius': {'type': 'number'}, 'humidity': {'type': 'number'}, 'pm2_a': {'properties': {'particles_03um': {'type': 'number'}, 'particles_05um': {'type': 'number'}, 'particles_100um': {'type': 'number'}, 'particles_10um': {'type': 'number'}, 'particles_25um': {'type': 'number'}, 'particles_50um': {'type': 'number'}, 'pm100_env': {'type': 'number'}, 'pm100_standard': {'type': 'number'}, 'pm10_env': {'type': 'number'}, 'pm10_standard': {'type': 'number'}, 'pm25_env': {'type': 'number'}, 'pm25_standard': {'type': 'number'}}, 'required': ['pm10_standard', 'pm25_standard', 'pm100_standard', 'pm10_env', 'pm25_env', 'pm100_env', 'particles_03um', 'particles_05um', 'particles_10um', 'particles_25um', 'particles_50um', 'particles_100um'], 'type': 'object'}, 'pm2_b': {'properties': {'particles_03um': {'type': 'number'}, 'particles_05um': {'type': 'number'}, 'particles_100um': {'type': 'number'}, 'particles_10um': {'type': 'number'}, 'particles_25um': {'type': 'number'}, 'particles_50um': {'type': 'number'}, 'pm100_env': {'type': 'number'}, 'pm100_standard': {'type': 'number'}, 'pm10_env': {'type': 'number'}, 'pm10_standard': {'type': 'number'}, 'pm25_env': {'type': 'number'}, 'pm25_standard': {'type': 'number'}}, 'required': ['pm10_standard', 'pm25_standard', 'pm100_standard', 'pm10_env', 'pm25_env', 'pm100_env', 'particles_03um', 'particles_05um', 'particles_10um', 'particles_25um', 'particles_50um', 'particles_100um'], 'type': 'object'}, 'pressure': {'type': 'number'}, 'voc': {'type': 'number'}}, 'required': ['celcius', 'humidity', 'pressure', 'voc', 'pm2_a', 'pm2_b'], 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='pressure',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
