# Generated by Django 4.2.14 on 2025-04-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensordata_payload_alter_sensordata_pm2_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
