# Generated by Django 4.2.4 on 2023-10-19 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0029_alter_calibration_monitor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AQview',
            fields=[
                ('monitor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitors.monitor')),
            ],
            bases=('monitors.monitor',),
        ),
    ]
