# Generated by Django 4.2.11 on 2024-07-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aqview',
            options={'verbose_name': 'AQview'},
        ),
    ]
