# Generated by Django 2.2.9 on 2020-05-25 05:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import resticus.encoders


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurpleAir',
            fields=[
                ('monitor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitors.Monitor')),
                ('purple_id', models.IntegerField(unique=True)),
                ('thingspeak_key', models.CharField(max_length=50)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=resticus.encoders.JSONEncoder)),
            ],
            bases=('monitors.monitor',),
        ),
    ]
