# Generated by Django 3.0.6 on 2020-06-04 00:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import resticus.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('purpleair', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpleair',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=resticus.encoders.JSONEncoder),
        ),
    ]
