# Generated by Django 3.0.6 on 2020-07-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purpleair', '0002_auto_20200604_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purpleair',
            name='purple_id',
        ),
        migrations.RemoveField(
            model_name='purpleair',
            name='thingspeak_key',
        ),
    ]
