# Generated by Django 3.2.16 on 2022-11-19 13:10

from django.db import migrations


def populate_purple_id(apps, schema_editor):
    PurpleAir = apps.get_model('purpleair', 'PurpleAir')
    for monitor in PurpleAir.objects.all():
        monitor.purple_id = monitor.data['sensor_index']
        monitor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('purpleair', '0004_purpleair_purple_id'),
    ]

    operations = [
        migrations.RunPython(populate_purple_id),
    ]
