# Generated by Django 3.2.16 on 2022-11-19 13:10

from django.db import migrations


def purple_id_to_field(apps, schema_editor):
    PurpleAir = apps.get_model('purpleair', 'PurpleAir')
    for monitor in PurpleAir.objects.all():
        monitor.purple_id = monitor.data['sensor_index']
        monitor.save()


def purple_id_to_data(apps, schema_editor):
    PurpleAir = apps.get_model('purpleair', 'PurpleAir')
    for monitor in PurpleAir.objects.all():
        monitor.data = {'sensor_index': monitor.purple_id}
        monitor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('purpleair', '0004_purpleair_purple_id'),
    ]

    operations = [
        migrations.RunPython(purple_id_to_field, purple_id_to_data),
    ]
