# Generated by Django 3.2.16 on 2022-11-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpleair', '0005_auto_20221119_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpleair',
            name='purple_id',
            field=models.IntegerField(unique=True),
        ),
    ]
