# Generated by Django 4.2.11 on 2024-07-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purpleair', '0006_alter_purpleair_purple_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purpleair',
            options={'verbose_name': 'PurpleAir'},
        ),
    ]
