# Generated by Django 4.2.22 on 2025-10-20 02:40

import camp.utils.fields.mac_addr
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purpleair', '0007_alter_purpleair_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purpleair',
            old_name='purple_id',
            new_name='sensor_id',
        ),
        migrations.AddField(
            model_name='purpleair',
            name='hardware_id',
            field=camp.utils.fields.mac_addr.MACAddressField(blank=True, null=True),
        ),
    ]
