# Generated by Django 5.2.15 on 2026-06-10 04:51

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0036_host_monitor_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.URLField(blank=True, max_length=100, verbose_name='URL')),
                ('key', models.CharField(max_length=100, verbose_name='API Key')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AQLite',
            fields=[
                ('monitor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitors.monitor')),
                ('device_id', models.CharField(help_text='Full device identifier, e.g. AQLite-1234', max_length=50, unique=True, verbose_name='Device ID')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitors', to='aqlite.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'AQLite',
            },
            bases=('monitors.monitor',),
        ),
    ]
