# Generated by Django 2.2.1 on 2019-05-03 09:13

import aqm.utils.validators
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(validators=[aqm.utils.validators.JSONSchemaValidator({'properties': {'barometric_pressure': {'type': 'number'}, 'celcius': {'type': 'number'}, 'humidity': {'type': 'number'}, 'pm2': {'properties': {'a': {'properties': {'particles_03um': {'type': 'number'}, 'particles_05um': {'type': 'number'}, 'particles_100um': {'type': 'number'}, 'particles_10um': {'type': 'number'}, 'particles_25um': {'type': 'number'}, 'particles_50um': {'type': 'number'}, 'pm100_env': {'type': 'number'}, 'pm100_standard': {'type': 'number'}, 'pm10_env': {'type': 'number'}, 'pm10_standard': {'type': 'number'}, 'pm25_env': {'type': 'number'}, 'pm25_standard': {'type': 'number'}}, 'required': ['pm10_standard', 'pm25_standard', 'pm100_standard', 'pm10_env', 'pm25_env', 'pm100_env', 'particles_03um', 'particles_05um', 'particles_10um', 'particles_25um', 'particles_50um', 'particles_100um'], 'type': 'object'}, 'b': {'properties': {'particles_03um': {'type': 'number'}, 'particles_05um': {'type': 'number'}, 'particles_100um': {'type': 'number'}, 'particles_10um': {'type': 'number'}, 'particles_25um': {'type': 'number'}, 'particles_50um': {'type': 'number'}, 'pm100_env': {'type': 'number'}, 'pm100_standard': {'type': 'number'}, 'pm10_env': {'type': 'number'}, 'pm10_standard': {'type': 'number'}, 'pm25_env': {'type': 'number'}, 'pm25_standard': {'type': 'number'}}, 'required': ['pm10_standard', 'pm25_standard', 'pm100_standard', 'pm10_env', 'pm25_env', 'pm100_env', 'particles_03um', 'particles_05um', 'particles_10um', 'particles_25um', 'particles_50um', 'particles_100um'], 'type': 'object'}}, 'required': ['a', 'b'], 'type': 'object'}, 'voc': {'type': 'number'}}, 'required': ['celcius', 'humidity', 'pm2'], 'type': 'object'})])),
                ('is_processed', models.BooleanField(default=False)),
                ('celcius', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('pm2', django.contrib.postgres.fields.jsonb.JSONField(null=True, validators=[aqm.utils.validators.JSONSchemaValidator({'properties': {'a': {'properties': {'particles_03um': {'type': 'number'}, 'particles_05um': {'type': 'number'}, 'particles_100um': {'type': 'number'}, 'particles_10um': {'type': 'number'}, 'particles_25um': {'type': 'number'}, 'particles_50um': {'type': 'number'}, 'pm100_env': {'type': 'number'}, 'pm100_standard': {'type': 'number'}, 'pm10_env': {'type': 'number'}, 'pm10_standard': {'type': 'number'}, 'pm25_env': {'type': 'number'}, 'pm25_standard': {'type': 'number'}}, 'required': ['pm10_standard', 'pm25_standard', 'pm100_standard', 'pm10_env', 'pm25_env', 'pm100_env', 'particles_03um', 'particles_05um', 'particles_10um', 'particles_25um', 'particles_50um', 'particles_100um'], 'type': 'object'}, 'b': {'properties': {'particles_03um': {'type': 'number'}, 'particles_05um': {'type': 'number'}, 'particles_100um': {'type': 'number'}, 'particles_10um': {'type': 'number'}, 'particles_25um': {'type': 'number'}, 'particles_50um': {'type': 'number'}, 'pm100_env': {'type': 'number'}, 'pm100_standard': {'type': 'number'}, 'pm10_env': {'type': 'number'}, 'pm10_standard': {'type': 'number'}, 'pm25_env': {'type': 'number'}, 'pm25_standard': {'type': 'number'}}, 'required': ['pm10_standard', 'pm25_standard', 'pm100_standard', 'pm10_env', 'pm25_env', 'pm100_env', 'particles_03um', 'particles_05um', 'particles_10um', 'particles_25um', 'particles_50um', 'particles_100um'], 'type': 'object'}}, 'required': ['a', 'b'], 'type': 'object'})])),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.Sensor')),
            ],
        ),
    ]
