# Generated by Django 4.2.14 on 2024-09-17 23:44

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0032_delete_calibration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sensor', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='monitors.monitor')),
            ],
            options={
                'ordering': ('-timestamp', 'sensor'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PM25',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sensor', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('pm25_reported', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pm25_calibrated', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('pm25_calibration_formula', models.TextField(blank=True, default='')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='monitors.monitor')),
            ],
            options={
                'ordering': ('-timestamp', 'sensor'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PM100',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sensor', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('pm100', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='monitors.monitor')),
            ],
            options={
                'ordering': ('-timestamp', 'sensor'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PM10',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sensor', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('pm10', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='monitors.monitor')),
            ],
            options={
                'ordering': ('-timestamp', 'sensor'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Particulates',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sensor', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('particles_03um', models.DecimalField(decimal_places=2, max_digits=8)),
                ('particles_05um', models.DecimalField(decimal_places=2, max_digits=8)),
                ('particles_10um', models.DecimalField(decimal_places=2, max_digits=8)),
                ('particles_25um', models.DecimalField(decimal_places=2, max_digits=8)),
                ('particles_50um', models.DecimalField(decimal_places=2, max_digits=8)),
                ('particles_100um', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='monitors.monitor')),
            ],
            options={
                'ordering': ('-timestamp', 'sensor'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ozone',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sensor', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('ozone', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='monitors.monitor')),
            ],
            options={
                'ordering': ('-timestamp', 'sensor'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sensor', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='monitors.monitor')),
            ],
            options={
                'ordering': ('-timestamp', 'sensor'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sensor', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('celsius', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fahrenheit', models.DecimalField(decimal_places=1, max_digits=5)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='monitors.monitor')),
            ],
            options={
                'ordering': ('-timestamp', 'sensor'),
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['timestamp', 'sensor'], name='entries_tem_timesta_1e308e_brin')],
            },
        ),
        migrations.AddConstraint(
            model_name='temperature',
            constraint=models.UniqueConstraint(fields=('monitor', 'timestamp', 'sensor'), name='unique_entry_temperature'),
        ),
        migrations.AddIndex(
            model_name='pressure',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['timestamp', 'sensor'], name='entries_pre_timesta_c20a4a_brin'),
        ),
        migrations.AddConstraint(
            model_name='pressure',
            constraint=models.UniqueConstraint(fields=('monitor', 'timestamp', 'sensor'), name='unique_entry_pressure'),
        ),
        migrations.AddIndex(
            model_name='pm25',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['timestamp', 'sensor'], name='entries_pm2_timesta_5eada9_brin'),
        ),
        migrations.AddConstraint(
            model_name='pm25',
            constraint=models.UniqueConstraint(fields=('monitor', 'timestamp', 'sensor'), name='unique_entry_pm25'),
        ),
        migrations.AddIndex(
            model_name='pm100',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['timestamp', 'sensor'], name='entries_pm1_timesta_d72793_brin'),
        ),
        migrations.AddConstraint(
            model_name='pm100',
            constraint=models.UniqueConstraint(fields=('monitor', 'timestamp', 'sensor'), name='unique_entry_pm100'),
        ),
        migrations.AddIndex(
            model_name='pm10',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['timestamp', 'sensor'], name='entries_pm1_timesta_c6efd5_brin'),
        ),
        migrations.AddConstraint(
            model_name='pm10',
            constraint=models.UniqueConstraint(fields=('monitor', 'timestamp', 'sensor'), name='unique_entry_pm10'),
        ),
        migrations.AddIndex(
            model_name='particulates',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['timestamp', 'sensor'], name='entries_par_timesta_2e5445_brin'),
        ),
        migrations.AddConstraint(
            model_name='particulates',
            constraint=models.UniqueConstraint(fields=('monitor', 'timestamp', 'sensor'), name='unique_entry_particulates'),
        ),
        migrations.AddIndex(
            model_name='ozone',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['timestamp', 'sensor'], name='entries_ozo_timesta_db2db9_brin'),
        ),
        migrations.AddConstraint(
            model_name='ozone',
            constraint=models.UniqueConstraint(fields=('monitor', 'timestamp', 'sensor'), name='unique_entry_ozone'),
        ),
        migrations.AddIndex(
            model_name='humidity',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['timestamp', 'sensor'], name='entries_hum_timesta_29654d_brin'),
        ),
        migrations.AddConstraint(
            model_name='humidity',
            constraint=models.UniqueConstraint(fields=('monitor', 'timestamp', 'sensor'), name='unique_entry_humidity'),
        ),
    ]
