# Generated by Django 4.2.20 on 2025-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_particulates_particles_03um_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm25',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='PM2.5 (µg/m³)', max_digits=7),
        ),
    ]
