# Generated by Django 5.2.15 on 2026-07-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_pm25_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Carbon dioxide (ppm)', max_digits=6),
        ),
    ]
