# Generated by Django 4.2.25 on 2026-02-24 22:37

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontalInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_type', models.CharField(choices=[('warm', 'Warm Front'), ('cold', 'Cold Front'), ('stationary', 'Stationary Front'), ('occluded', 'Occluded Front')], help_text='Type of weather front', max_length=20)),
                ('front_direction', models.FloatField(blank=True, help_text='Direction of front movement (degrees, 0-360)', null=True)),
                ('front_speed', models.FloatField(blank=True, help_text='Speed of front movement (m/s)', null=True)),
                ('warm_air_temperature', models.FloatField(help_text='Warm air mass temperature (°C)')),
                ('cold_air_temperature', models.FloatField(help_text='Cold air mass temperature (°C)')),
            ],
            options={
                'ordering': ['-inversion__detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('inversion_type', models.CharField(choices=[('radiation', 'Radiation Inversion'), ('subsidence', 'Subsidence Inversion'), ('frontal', 'Frontal Inversion')], help_text='Type of atmospheric inversion', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('watch', 'Inversion Watch (6-12 hours)'), ('advisory', 'Inversion Advisory (12-48 hours)'), ('persistent', 'Persistent Inversion Event (48+ hours)')], help_text='Severity classification based on duration and PM2.5 confirmation', max_length=20, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='Time range during which the inversion was detected')),
                ('temperature_gradient', models.FloatField(help_text='Temperature difference between surface and upper air (°C)')),
                ('surface_temperature', models.FloatField(help_text='Surface temperature (°C)')),
                ('upper_air_temperature', models.FloatField(help_text='Upper air temperature (°C)')),
                ('wind_speed', models.FloatField(help_text='Wind speed (m/s)')),
                ('pressure', models.FloatField(help_text='Atmospheric pressure (hPa)')),
                ('boundary_layer_height', models.FloatField(blank=True, help_text='Planetary boundary layer height (meters)', null=True)),
                ('strength', models.FloatField(help_text='Strength of inversion (temperature gradient magnitude)')),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence level of detection (0-1)')),
                ('pm25_confirmed', models.BooleanField(default=False, help_text='Whether pollution trapping was confirmed by PM2.5 behavior')),
                ('pm25_night_mean', models.FloatField(blank=True, help_text='Mean PM2.5 during nighttime hours (μg/m³)', null=True)),
                ('pm25_day_mean', models.FloatField(blank=True, help_text='Mean PM2.5 during daytime hours (μg/m³)', null=True)),
                ('pm25_previous_day_mean', models.FloatField(blank=True, help_text='Mean PM2.5 from previous day for trend analysis (μg/m³)', null=True)),
                ('pm25_night_day_ratio', models.FloatField(blank=True, help_text='Ratio of nighttime to daytime PM2.5', null=True)),
                ('persistence_hours', models.IntegerField(default=0, help_text='Number of consecutive hours with inversion conditions')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SubsidenceInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure_system', models.CharField(choices=[('high', 'High Pressure'), ('low', 'Low Pressure')], default='high', max_length=20)),
                ('subsidence_rate', models.FloatField(blank=True, help_text='Rate of air descent (Pa/s or hPa/hour)', null=True)),
                ('inversion_height', models.FloatField(help_text='Height of inversion layer (meters above ground)')),
                ('layer_thickness', models.FloatField(blank=True, help_text='Thickness of inversion layer (meters)', null=True)),
                ('inversion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subsidence_details', to='inversions.inversion')),
            ],
            options={
                'ordering': ['-inversion__detected_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiationInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_cover', models.FloatField(help_text='Cloud cover percentage (0-100)')),
                ('solar_radiation', models.FloatField(help_text='Solar radiation (W/m²)')),
                ('time_of_day', models.CharField(choices=[('night', 'Night'), ('dawn', 'Dawn'), ('day', 'Day')], help_text='Time period when detected', max_length=10)),
                ('ground_cooling_rate', models.FloatField(blank=True, help_text='Rate of ground cooling (°C/hour)', null=True)),
                ('inversion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='radiation_details', to='inversions.inversion')),
            ],
            options={
                'ordering': ['-inversion__detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inversion',
            index=models.Index(fields=['inversion_type', '-detected_at'], name='inversions__inversi_c55df3_idx'),
        ),
        migrations.AddIndex(
            model_name='inversion',
            index=models.Index(fields=['is_active', '-detected_at'], name='inversions__is_acti_92bf36_idx'),
        ),
        migrations.AddIndex(
            model_name='inversion',
            index=models.Index(fields=['pm25_confirmed', '-detected_at'], name='inversions__pm25_co_52e667_idx'),
        ),
        migrations.AddIndex(
            model_name='inversion',
            index=models.Index(fields=['severity', '-detected_at'], name='inversions__severit_6093ae_idx'),
        ),
        migrations.AddField(
            model_name='frontalinversion',
            name='inversion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frontal_details', to='inversions.inversion'),
        ),
    ]
