# Generated by Django 4.2.29 on 2026-03-11 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CES4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(null=True, verbose_name='Total Population')),
                ('ci_score', models.FloatField(null=True, verbose_name='CES Score')),
                ('ci_score_p', models.FloatField(null=True, verbose_name='CES Score Percentile')),
                ('dac_sb535', models.BooleanField(null=True, verbose_name='SB535 DAC')),
                ('dac_category', models.IntegerField(blank=True, choices=[(1, 'Top 25% CES overall score'), (2, 'Top 5% pollution burden (no overall score)'), (3, 'Designated under 2017 DAC list'), (4, 'Federally recognized Tribal land')], null=True, verbose_name='DAC Category')),
                ('pollution', models.FloatField(null=True, verbose_name='Pollution Burden Score')),
                ('pollution_s', models.FloatField(null=True, verbose_name='Pollution Burden Score (scaled)')),
                ('pollution_p', models.FloatField(null=True, verbose_name='Pollution Burden Percentile')),
                ('pol_ozone', models.FloatField(null=True, verbose_name='Ozone')),
                ('pol_ozone_p', models.FloatField(null=True, verbose_name='Ozone Percentile')),
                ('pol_pm', models.FloatField(null=True, verbose_name='PM2.5')),
                ('pol_pm_p', models.FloatField(null=True, verbose_name='PM2.5 Percentile')),
                ('pol_diesel', models.FloatField(null=True, verbose_name='Diesel PM')),
                ('pol_diesel_p', models.FloatField(null=True, verbose_name='Diesel PM Percentile')),
                ('pol_pest', models.FloatField(null=True, verbose_name='Pesticides')),
                ('pol_pest_p', models.FloatField(null=True, verbose_name='Pesticides Percentile')),
                ('pol_rsei_haz', models.FloatField(null=True, verbose_name='Toxic Releases (RSEI)')),
                ('pol_rsei_haz_p', models.FloatField(null=True, verbose_name='Toxic Releases Percentile')),
                ('pol_traffic', models.FloatField(null=True, verbose_name='Traffic')),
                ('pol_traffic_p', models.FloatField(null=True, verbose_name='Traffic Percentile')),
                ('pol_drink', models.FloatField(null=True, verbose_name='Drinking Water Contaminants')),
                ('pol_drink_p', models.FloatField(null=True, verbose_name='Drinking Water Contaminants Percentile')),
                ('pol_haz', models.FloatField(null=True, verbose_name='Hazardous Waste')),
                ('pol_haz_p', models.FloatField(null=True, verbose_name='Hazardous Waste Percentile')),
                ('pol_lead', models.FloatField(null=True, verbose_name='Lead')),
                ('pol_lead_p', models.FloatField(null=True, verbose_name='Lead Percentile')),
                ('pol_cleanups', models.FloatField(null=True, verbose_name='Cleanup Sites')),
                ('pol_cleanups_p', models.FloatField(null=True, verbose_name='Cleanup Sites Percentile')),
                ('pol_gwthreats', models.FloatField(null=True, verbose_name='Groundwater Threats')),
                ('pol_gwthreats_p', models.FloatField(null=True, verbose_name='Groundwater Threats Percentile')),
                ('pol_iwb', models.FloatField(null=True, verbose_name='Impaired Water Bodies')),
                ('pol_iwb_p', models.FloatField(null=True, verbose_name='Impaired Water Bodies Percentile')),
                ('pol_swis', models.FloatField(null=True, verbose_name='Solid Waste Sites')),
                ('pol_swis_p', models.FloatField(null=True, verbose_name='Solid Waste Sites Percentile')),
                ('popchar', models.FloatField(null=True, verbose_name='Population Characteristics Score')),
                ('popchar_s', models.FloatField(null=True, verbose_name='Population Characteristics Score (scaled)')),
                ('popchar_p', models.FloatField(null=True, verbose_name='Population Characteristics Percentile')),
                ('char_asthma', models.FloatField(null=True, verbose_name='Asthma')),
                ('char_asthma_p', models.FloatField(null=True, verbose_name='Asthma Percentile')),
                ('char_cvd', models.FloatField(null=True, verbose_name='Cardiovascular Disease')),
                ('char_cvd_p', models.FloatField(null=True, verbose_name='Cardiovascular Disease Percentile')),
                ('char_lbw', models.FloatField(null=True, verbose_name='Low Birth Weight')),
                ('char_lbw_p', models.FloatField(null=True, verbose_name='Low Birth Weight Percentile')),
                ('char_edu', models.FloatField(null=True, verbose_name='Educational Attainment')),
                ('char_edu_p', models.FloatField(null=True, verbose_name='Educational Attainment Percentile')),
                ('char_ling', models.FloatField(null=True, verbose_name='Linguistic Isolation')),
                ('char_ling_p', models.FloatField(null=True, verbose_name='Linguistic Isolation Percentile')),
                ('char_pov', models.FloatField(null=True, verbose_name='Poverty')),
                ('char_pov_p', models.FloatField(null=True, verbose_name='Poverty Percentile')),
                ('char_unemp', models.FloatField(null=True, verbose_name='Unemployment')),
                ('char_unemp_p', models.FloatField(null=True, verbose_name='Unemployment Percentile')),
                ('char_housingb', models.FloatField(null=True, verbose_name='Housing Burden')),
                ('char_housingb_p', models.FloatField(null=True, verbose_name='Housing Burden Percentile')),
                ('pop_under_10', models.IntegerField(null=True, verbose_name='Population Under 10')),
                ('pop_10_64', models.IntegerField(null=True, verbose_name='Population 10–64')),
                ('pop_65_plus', models.IntegerField(null=True, verbose_name='Population 65+')),
                ('pop_hispanic', models.IntegerField(null=True, verbose_name='Hispanic Population')),
                ('pop_white', models.IntegerField(null=True, verbose_name='White Population')),
                ('pop_black', models.IntegerField(null=True, verbose_name='Black or African American Population')),
                ('pop_native', models.IntegerField(null=True, verbose_name='American Indian and Alaska Native Population')),
                ('pop_aapi', models.IntegerField(null=True, verbose_name='Asian American and Pacific Islander Population')),
                ('pop_other', models.IntegerField(null=True, verbose_name='Other or Multiple Races Population')),
                ('boundary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='regions.boundary')),
            ],
            options={
                'verbose_name': 'CalEnviroScreen 4.0',
                'verbose_name_plural': 'CalEnviroScreen 4.0 Records',
                'abstract': False,
            },
        ),
    ]
