# Generated by Django 5.2.15 on 2026-07-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ces4',
            options={'ordering': ['boundary__region__external_id'], 'verbose_name': 'CalEnviroScreen 4.0', 'verbose_name_plural': 'CalEnviroScreen 4.0 Records'},
        ),
        migrations.AlterField(
            model_name='ces4',
            name='dac_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Top 25% CES overall score'), (2, 'Top 5% pollution burden (no overall score)'), (3, 'Carried over from prior DAC designation'), (4, 'Federally recognized Tribal land')], null=True, verbose_name='DAC Category'),
        ),
    ]
