# Generated by Django 3.1.1 on 2020-10-16 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0014_remove_entry_pm100_aqi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirNow',
            fields=[
                ('monitor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitors.monitor')),
            ],
            bases=('monitors.monitor',),
        ),
    ]
