# Generated by Django 3.2.11 on 2022-01-31 00:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210730_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tl', 'Filipino'), ('hmn', 'Hmong'), ('es', 'Spanish')], default='en', verbose_name='Preferred language', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Your cell phone number for receiving air quality text alerts.', max_length=128, region=None),
        ),
    ]
