# Generated by Django 4.2.4 on 2024-02-06 06:59

import camp.utils.fields
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=camp.utils.fields.NullEmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='Your cell phone number for receiving air quality text alerts.', max_length=128, region=None, unique=True),
        ),
    ]
