# Generated by Django 5.2.16 on 2026-10-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_date_joined_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_blocked',
            field=models.BooleanField(db_default=False, default=False, verbose_name='SMS blocked by carrier opt-out'),
        ),
    ]
