# Generated by Django 3.2.4 on 2021-06-07 11:44

import camp.apps.monitors.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_smalluuid.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0017_auto_20210312_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(db_index=True)),
                ('r2', models.FloatField()),
                ('formula', models.CharField(blank=True, default='', max_length=255, validators=[camp.apps.monitors.validators.validate_formula])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calibrator',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('calibration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrator_current', to='calibrations.calibration')),
                ('colocated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colocated_calibrator', to='monitors.monitor')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_calibrator', to='monitors.monitor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='calibration',
            name='calibrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='calibrations.calibrator'),
        ),
    ]
