# Generated by Django 3.2.16 on 2022-12-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0003_delete_countycalibration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrator',
            old_name='is_active',
            new_name='is_enabled',
        ),
    ]
