# Generated by Django 4.2.14 on 2025-04-19 21:06

import camp.apps.entries.fields
import camp.apps.monitors.fields
from django.db import migrations, models
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0004_rename_is_active_calibrator_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCalibration',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('monitor_type', camp.apps.monitors.fields.MonitorTypeField(max_length=50)),
                ('entry_type', camp.apps.entries.fields.EntryTypeField(max_length=50)),
                ('calibration', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'unique_together': {('monitor_type', 'entry_type')},
            },
        ),
    ]
