# Generated by Django 4.2.20 on 2025-07-29 05:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('type', models.CharField(choices=[('city', 'City'), ('county', 'County'), ('zipcode', 'ZIP Code'), ('tract', 'Census Tract'), ('cdp', 'Census Designated Place'), ('school_district', 'School District'), ('congressional_district', 'Congressional District'), ('state_assembly', 'State Assembly District'), ('state_senate', 'State Senate District'), ('custom', 'Custom Region')], db_index=True, max_length=32)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
    ]
