# Generated by Django 4.2.20 on 2025-07-26 21:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('type', models.CharField(choices=[('city', 'City'), ('county', 'County'), ('zipcode', 'ZIP Code'), ('tract', 'Census Tract'), ('cdp', 'Census Designated Place'), ('school_district', 'School District'), ('congressional_district', 'Congressional District'), ('state_assembly', 'State Assembly District'), ('state_senate', 'State Senate District'), ('custom', 'Custom Region')], max_length=32)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='regions_reg_type_7693f0_idx'), models.Index(fields=['name'], name='regions_reg_name_0bb589_idx'), models.Index(fields=['type', 'name'], name='regions_reg_type_65ba48_idx')],
                'unique_together': {('name', 'type')},
            },
        ),
    ]
