# Generated by Django 4.2.20 on 2025-08-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundary',
            name='record',
        ),
    ]
