# Generated by Django 4.2.29 on 2026-05-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_enable_pg_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='type',
            field=models.CharField(choices=[('county', 'County'), ('city', 'City'), ('zipcode', 'ZIP Code'), ('tract', 'Census Tract'), ('cdp', 'Census Designated Place'), ('congressional_district', 'Congressional District'), ('state_assembly', 'State Assembly District'), ('state_senate', 'State Senate District'), ('school_district', 'School District'), ('urban_area', 'Urban Area'), ('land_use', 'Land Use'), ('protected', 'Protected Area'), ('place', 'Place'), ('mtrs', 'MTRS Section'), ('custom', 'Custom Region')], db_index=True, max_length=32),
        ),
    ]
