# Generated by Django 4.2.29 on 2026-05-11 06:24

import camp.utils.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_add_mtrs_region_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=camp.utils.encoders.JSONEncoder),
        ),
    ]
