# Generated by Django 5.2.16 on 2026-09-21 08:11

import camp.utils.encoders
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_region_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('public_school', 'Public School'), ('private_school', 'Private School'), ('child_care', 'Child Care')], db_index=True, max_length=32, verbose_name='Type')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('external_id', models.CharField(max_length=64, verbose_name='External ID')),
                ('source', models.CharField(max_length=32, verbose_name='Source')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('zip', models.CharField(blank=True, max_length=10, verbose_name='ZIP Code')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=camp.utils.encoders.JSONEncoder)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Imported At')),
                ('county', models.ForeignKey(blank=True, limit_choices_to={'type': 'county'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='regions.region', verbose_name='County')),
                ('district', models.ForeignKey(blank=True, limit_choices_to={'type': 'school_district'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='regions.region', verbose_name='School District')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
