# Generated by Django 5.2.16 on 2026-09-25 19:42

from django.db import migrations


def delete_place_regions(apps, schema_editor):
    """
    Drop the synthetic 'place' regions (build_places' union of an urban area
    and its cities and CDPs); the real layers are shown instead. Their
    boundaries go first: Boundary.region cascades anyway, but Region.boundary
    points back at one, so deleting the boundaries explicitly keeps the
    order plain.
    """
    Region = apps.get_model('regions', 'Region')
    Boundary = apps.get_model('regions', 'Boundary')
    Boundary.objects.filter(region__type='place').delete()
    Region.objects.filter(type='place').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0008_region_type_air_district'),
    ]

    operations = [
        migrations.RunPython(delete_place_regions, migrations.RunPython.noop),
    ]
