# Generated by Django 4.2.29 on 2026-03-13 04:28

import camp.apps.entries.fields
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        ('monitors', '0036_host_monitor_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionSummary',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('resolution', models.CharField(choices=[('hour', 'Hourly'), ('day', 'Daily'), ('month', 'Monthly'), ('quarter', 'Quarterly'), ('season', 'Seasonal'), ('year', 'Yearly')], max_length=10, verbose_name='resolution')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('entry_type', camp.apps.entries.fields.EntryTypeField(max_length=50)),
                ('count', models.PositiveIntegerField(verbose_name='count')),
                ('expected_count', models.PositiveIntegerField(verbose_name='expected count')),
                ('sum_value', models.FloatField(verbose_name='sum')),
                ('sum_of_squares', models.FloatField(verbose_name='sum of squares')),
                ('tdigest', models.JSONField(verbose_name='t-digest')),
                ('minimum', models.FloatField(verbose_name='minimum')),
                ('maximum', models.FloatField(verbose_name='maximum')),
                ('mean', models.FloatField(verbose_name='mean')),
                ('stddev', models.FloatField(verbose_name='standard deviation')),
                ('p25', models.FloatField(verbose_name='25th percentile')),
                ('p75', models.FloatField(verbose_name='75th percentile')),
                ('is_complete', models.BooleanField(default=False, help_text='True if count >= 80% of expected_count.', verbose_name='is complete')),
                ('station_count', models.PositiveIntegerField(verbose_name='station count')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='regions.region')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['timestamp', 'resolution', 'entry_type'], name='summaries_r_timesta_df51f7_idx')],
                'unique_together': {('region', 'entry_type', 'resolution', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='MonitorSummary',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('resolution', models.CharField(choices=[('hour', 'Hourly'), ('day', 'Daily'), ('month', 'Monthly'), ('quarter', 'Quarterly'), ('season', 'Seasonal'), ('year', 'Yearly')], max_length=10, verbose_name='resolution')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('entry_type', camp.apps.entries.fields.EntryTypeField(max_length=50)),
                ('count', models.PositiveIntegerField(verbose_name='count')),
                ('expected_count', models.PositiveIntegerField(verbose_name='expected count')),
                ('sum_value', models.FloatField(verbose_name='sum')),
                ('sum_of_squares', models.FloatField(verbose_name='sum of squares')),
                ('tdigest', models.JSONField(verbose_name='t-digest')),
                ('minimum', models.FloatField(verbose_name='minimum')),
                ('maximum', models.FloatField(verbose_name='maximum')),
                ('mean', models.FloatField(verbose_name='mean')),
                ('stddev', models.FloatField(verbose_name='standard deviation')),
                ('p25', models.FloatField(verbose_name='25th percentile')),
                ('p75', models.FloatField(verbose_name='75th percentile')),
                ('is_complete', models.BooleanField(default=False, help_text='True if count >= 80% of expected_count.', verbose_name='is complete')),
                ('processor', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='processor')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='monitors.monitor')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['timestamp', 'resolution', 'entry_type'], name='summaries_m_timesta_f785ec_idx')],
                'unique_together': {('monitor', 'entry_type', 'processor', 'resolution', 'timestamp')},
            },
        ),
    ]
