# Generated by Django 4.2.29 on 2026-03-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0036_host_monitor_host'),
        ('regions', '0001_initial'),
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monitorsummary',
            unique_together={('monitor', 'entry_type', 'processor', 'resolution', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='regionsummary',
            unique_together={('region', 'entry_type', 'processor', 'resolution', 'timestamp')},
        ),
        migrations.RemoveField(
            model_name='monitorsummary',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='regionsummary',
            name='stage',
        ),
    ]
