# Generated by Django 4.2.29 on 2026-04-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorsummary',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='is complete'),
        ),
        migrations.AlterField(
            model_name='regionsummary',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='is complete'),
        ),
        migrations.AddIndex(
            model_name='monitorsummary',
            index=models.Index(fields=['resolution', 'timestamp'], name='summaries_m_resolut_54c3db_idx'),
        ),
        migrations.AddIndex(
            model_name='regionsummary',
            index=models.Index(fields=['resolution', 'timestamp'], name='summaries_r_resolut_b00d5d_idx'),
        ),
    ]
