# Generated by Django 4.2.29 on 2026-03-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('summaries', '0002_remove_stage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regionsummary',
            unique_together={('region', 'entry_type', 'resolution', 'timestamp')},
        ),
        migrations.RemoveField(
            model_name='regionsummary',
            name='processor',
        ),
    ]
