# Generated by Django 4.2.30 on 2026-05-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_add_resolution_timestamp_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionsummary',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='weight'),
        ),
        # Backfill existing records: use count as a best-effort weight.
        # New records will store the exact float total_weight from compute_region_summary.
        migrations.RunSQL(
            sql='UPDATE summaries_regionsummary SET weight = "count"',
            reverse_sql='',
        ),
    ]
