# Generated by Django 4.2.30 on 2026-05-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0003_add_weight_to_region_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionsummary',
            name='is_complete',
        ),
    ]
