# Generated by Django 5.2.15 on 2026-07-13 17:16

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0004_remove_is_complete_from_region_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryBackfillJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('done', 'Done'), ('failed', 'Failed')], default='running', max_length=10, verbose_name='state')),
                ('phase', models.CharField(choices=[('idle', 'Idle'), ('monitors', 'Monitors'), ('regions', 'Regions')], default='idle', max_length=10, verbose_name='phase')),
                ('cursor', models.DateTimeField(verbose_name='cursor')),
                ('chunk_start', models.DateTimeField(blank=True, null=True, verbose_name='chunk start')),
                ('range_start', models.DateTimeField(verbose_name='range start')),
                ('range_end', models.DateTimeField(verbose_name='range end')),
                ('pending_tasks', models.PositiveIntegerField(default=0, verbose_name='pending tasks')),
                ('batch_id', models.PositiveIntegerField(default=0, verbose_name='batch id')),
                ('phase_started_at', models.DateTimeField(blank=True, null=True, verbose_name='phase started at')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='locked at')),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0, verbose_name='consecutive failures')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='last error')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
