# Generated by Django 5.2.15 on 2026-07-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0005_summarybackfilljob'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarybackfilljob',
            name='chunk_days',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='chunk days'),
        ),
    ]
