# Generated by Django 3.2.16 on 2023-01-09 08:29

import camp.apps.archive.models
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0024_auto_20221214_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryArchive',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(validators=[camp.apps.archive.models.year_validator])),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('data', models.FileField(upload_to=camp.apps.archive.models.archive_data_path)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='monitors.monitor')),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
        migrations.AddIndex(
            model_name='entryarchive',
            index=models.Index(fields=['monitor', 'year', 'month'], name='archive_ent_monitor_431cde_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryarchive',
            constraint=models.UniqueConstraint(fields=('monitor', 'year', 'month'), name='unique_archive'),
        ),
    ]
