# Generated by Django 5.2.15 on 2026-07-12 08:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0005_region_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('zone_name', models.CharField(max_length=64, verbose_name='zone name')),
                ('forecast_date', models.DateField(verbose_name='forecast date')),
                ('issued_date', models.DateField(verbose_name='issued date')),
                ('published_at', models.DateTimeField(verbose_name='published at')),
                ('aqi_value', models.PositiveSmallIntegerField(verbose_name='AQI value')),
                ('aqi_category', models.CharField(max_length=32, verbose_name='AQI category')),
                ('pollutant', models.CharField(choices=[('O3', 'Ozone'), ('PM2.5', 'PM2.5')], max_length=16, verbose_name='pollutant')),
                ('burn_status', models.CharField(max_length=32, verbose_name='burn status')),
                ('burn_status_text', models.CharField(max_length=255, verbose_name='burn status text')),
                ('air_alert', models.BooleanField(default=False, verbose_name='air alert')),
                ('air_alert_start', models.DateField(blank=True, null=True, verbose_name='air alert start')),
                ('air_alert_end', models.DateField(blank=True, null=True, verbose_name='air alert end')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='regions.region')),
            ],
            options={
                'ordering': ('-issued_date', 'region__name'),
                'indexes': [models.Index(fields=['region', 'forecast_date'], name='forecasts_f_region__b2667f_idx'), models.Index(fields=['issued_date'], name='forecasts_f_issued__f350a8_idx')],
            },
        ),
    ]
