# Generated by Django 5.2.15 on 2026-07-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='burn_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='burn status'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='burn_status_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='burn status text'),
        ),
    ]
