# Generated by Django 3.1.1 on 2021-03-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0017_auto_20210312_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Methane',
            fields=[
                ('monitor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitors.monitor')),
            ],
            options={
                'verbose_name': 'Methane',
            },
            bases=('monitors.monitor',),
        ),
    ]
