# Generated by Django 4.2.14 on 2025-04-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methane', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Methane',
        ),
    ]
