# Generated by Django 2.2.9 on 2020-05-25 05:17

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_smalluuid.models
import resticus.encoders


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('position', django.contrib.gis.db.models.fields.PointField(db_index=True, null=True, srid=4326)),
                ('location', models.CharField(choices=[('inside', 'inside'), ('outside', 'outside')], max_length=10)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=resticus.encoders.JSONEncoder)),
                ('celcius', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('fahrenheit', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('pm100_env', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pm10_env', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pm25_env', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pm100_standard', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pm10_standard', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pm25_standard', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('particles_03um', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('particles_05um', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('particles_100um', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('particles_10um', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('particles_25um', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('particles_50um', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('epa_pm25_aqi', models.IntegerField(null=True)),
                ('epa_pm100_aqi', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(db_index=True, null=True, srid=4326)),
                ('location', models.CharField(choices=[('inside', 'inside'), ('outside', 'outside')], max_length=10)),
                ('latest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_latest', to='monitors.Entry')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='monitors.Monitor'),
        ),
    ]
