# Generated by Django 2.2.9 on 2020-05-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('monitor', 'timestamp'), name='unique_entry'),
        ),
    ]
