# Generated by Django 3.0.6 on 2020-06-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_auto_20200531_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pm100_env',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm100_standard',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm10_env',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm10_standard',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm25_env',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm25_standard',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
