# Generated by Django 3.0.6 on 2020-07-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_entry_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pm25_calibration_formula',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='monitor',
            name='pm25_calibration_formula',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='monitor',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='epa_pm100_aqi',
            new_name='pm100_aqi',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='epa_pm25_aqi',
            new_name='pm25_aqi',
        ),
    ]
