# Generated by Django 3.0.6 on 2020-07-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0005_auto_20200727_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pm25_avg_15',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='pm25_avg_60',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
