# Generated by Django 3.0.6 on 2020-07-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0006_auto_20200729_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='is_sjvair',
            field=models.BooleanField(default=False, help_text='Is this monitor part of the SJVAir network?'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hides the monitor on the map.'),
        ),
    ]
