# Generated by Django 3.0.6 on 2020-08-09 22:47

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0007_auto_20200731_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['timestamp'], name='monitors_en_timesta_e6bc1b_brin'),
        ),
    ]
