# Generated by Django 3.0.6 on 2020-08-09 23:27

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0008_auto_20200809_2247'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entry',
            name='unique_entry',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='monitors_en_timesta_e6bc1b_brin',
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['timestamp', 'sensor'], name='monitors_en_timesta_f78240_brin'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('monitor', 'timestamp', 'sensor'), name='unique_entry'),
        ),
    ]
