# Generated by Django 3.0.7 on 2020-08-23 00:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import resticus.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0009_auto_20200809_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='latest',
        ),
        migrations.AddField(
            model_name='monitor',
            name='latest',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=resticus.encoders.JSONEncoder),
        ),
    ]
