# Generated by Django 3.0.9 on 2020-08-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0011_auto_20200824_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='county',
            field=models.CharField(blank=True, choices=[('Fresno', 'Fresno'), ('Madera', 'Madera'), ('Merced', 'Merced'), ('Tulare', 'Tulare'), ('Stanislaus', 'Stanislaus'), ('Kern', 'Kern'), ('Kings', 'Kings'), ('San Joaquin', 'San Joaquin')], max_length=20),
        ),
    ]
