# Generated by Django 3.0.9 on 2020-08-30 02:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0012_monitor_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='access_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
