# Generated by Django 3.1.1 on 2020-12-27 05:41

import camp.apps.monitors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0015_auto_20201217_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='pm25_formula',
            field=models.CharField(blank=True, default='', max_length=255, validators=[camp.apps.monitors.validators.validate_formula]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='celcius',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='fahrenheit',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='humidity',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='particles_03um',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='particles_05um',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='particles_100um',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='particles_10um',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='particles_25um',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='particles_50um',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm100_env',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm100_standard',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm10_env',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm10_standard',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm25_avg_15',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm25_avg_60',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm25_env',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pm25_standard',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pressure',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='pm25_calibration_formula',
            field=models.CharField(blank=True, default='', max_length=255, validators=[camp.apps.monitors.validators.validate_formula]),
        ),
    ]
