# Generated by Django 3.1.1 on 2021-03-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0016_auto_20201227_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='monitor_type',
            field=models.CharField(choices=[('airnow', 'airnow'), ('bam1022', 'bam1022'), ('methane', 'methane'), ('purpleair', 'purpleair')], max_length=20),
        ),
    ]
