# Generated by Django 3.2.5 on 2021-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0017_auto_20210312_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes for internal use.'),
        ),
    ]
