# Generated by Django 3.2.5 on 2021-12-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0018_monitor_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='default_sensor',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
