# Generated by Django 3.2.5 on 2022-01-29 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0019_monitor_default_sensor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('sensor', '-timestamp')},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='pm100_env',
            new_name='pm10',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='pm10_env',
            new_name='pm100',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='pm25_env',
            new_name='pm25',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='pm100_standard',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='pm10_standard',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='pm25_aqi',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='pm25_standard',
        ),
    ]
