# Generated by Django 3.2.5 on 2022-01-30 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0020_auto_20220129_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='latest',
        ),
        migrations.AddField(
            model_name='monitor',
            name='latest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_for', to='monitors.entry'),
        ),
    ]
