# Generated by Django 3.2.16 on 2022-11-21 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0021_refactor_monitor_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='payload',
        ),
    ]
