# Generated by Django 3.2.16 on 2022-12-14 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0023_rename_celcius_entry_celsius'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'base_manager_name': 'objects', 'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='entry',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
