# Generated by Django 3.2.16 on 2023-07-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0024_auto_20221214_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-timestamp', 'sensor')},
        ),
        migrations.AddField(
            model_name='entry',
            name='pm25_reported',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
