# Generated by Django 4.2.4 on 2023-09-25 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaqc', '0001_initial'),
        ('monitors', '0027_monitor_current_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='current_health',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for', to='qaqc.sensoranalysis'),
        ),
    ]
