# Generated by Django 4.2.4 on 2023-10-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0028_alter_monitor_current_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='monitor_type',
            field=models.CharField(choices=[('airnow', 'airnow'), ('aqview', 'aqview'), ('bam1022', 'bam1022'), ('methane', 'methane'), ('purpleair', 'purpleair')], max_length=20),
        ),
    ]
