# Generated by Django 4.2.4 on 2024-01-23 00:56

from django.db import migrations, models
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0029_alter_calibration_monitor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monitors', models.ManyToManyField(blank=True, related_name='groups', to='monitors.monitor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
