# Generated by Django 4.2.4 on 2024-02-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0030_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='data_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='monitor',
            name='data_provider_url',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='monitor',
            name='device',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
