# Generated by Django 4.2.14 on 2024-09-09 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0031_monitor_data_provider_monitor_data_provider_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calibration',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='pm25_calibration_formula',
        ),
    ]
