# Generated by Django 4.2.14 on 2024-11-14 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
        ('monitors', '0032_delete_calibration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='co',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_latest_for', to='entries.co'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='humidity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='humidity_latest_for', to='entries.humidity'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='no2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no2_latest_for', to='entries.no2'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='o3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o3_latest_for', to='entries.o3'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='particulates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='particulates_latest_for', to='entries.particulates'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='pm10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm10_latest_for', to='entries.pm10'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='pm100',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm100_latest_for', to='entries.pm100'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='pm25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm25_latest_for', to='entries.pm25'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='pressure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pressure_latest_for', to='entries.pressure'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='temperature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_latest_for', to='entries.temperature'),
        ),
    ]
