# Generated by Django 4.2.14 on 2025-04-09 17:07

from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('monitors', '0032_delete_calibration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSensor',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('sensor', models.CharField(blank=True, max_length=50, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_sensors', to='monitors.monitor')),
            ],
            options={
                'unique_together': {('monitor', 'content_type')},
            },
        ),
    ]
