# Generated by Django 4.2.14 on 2024-09-17 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
        ('monitors', '0032_delete_calibration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='humidity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='humidity_latest_for', to='entries.humidity'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='ozone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ozone_latest_for', to='entries.ozone'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='pm10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm10_latest_for', to='entries.pm10'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='pm100',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm100_latest_for', to='entries.pm100'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='pm25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm25_latest_for', to='entries.pm25'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='pressure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pressure_latest_for', to='entries.pressure'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='temperature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_latest_for', to='entries.temperature'),
        ),
    ]
