# Generated by Django 4.2.14 on 2025-04-27 00:52

import camp.apps.entries.fields
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0032_delete_calibration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestEntry',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('entry_type', camp.apps.entries.fields.EntryTypeField(max_length=50)),
                ('entry_id', django_smalluuid.models.SmallUUIDField(unique=True)),
                ('stage', models.CharField(choices=[('raw', 'Raw'), ('corrected', 'Corrected'), ('cleaned', 'Cleaned'), ('calibrated', 'Calibrated')], default='raw', max_length=16)),
                ('processor', models.CharField(blank=True, default='', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_entries', to='monitors.monitor')),
            ],
            options={
                'unique_together': {('monitor', 'entry_type', 'processor')},
            },
        ),
        migrations.CreateModel(
            name='DefaultSensor',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('entry_type', camp.apps.entries.fields.EntryTypeField(max_length=50)),
                ('sensor', models.CharField(blank=True, max_length=50, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_sensors', to='monitors.monitor')),
            ],
            options={
                'unique_together': {('monitor', 'entry_type')},
            },
        ),
    ]
