# Generated by Django 4.2.20 on 2025-07-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0033_latestentry_defaultsensor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultSensor',
        ),
    ]
