# Generated by Django 4.2.14 on 2025-04-11 19:01

from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('monitors', '0033_defaultsensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestEntry',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('object_id', django_smalluuid.models.SmallUUIDField(unique=True)),
                ('calibration', models.CharField(blank=True, default='', max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_entries', to='monitors.monitor')),
            ],
            options={
                'unique_together': {('monitor', 'content_type', 'calibration')},
            },
        ),
    ]
