# Generated by Django 4.2.14 on 2025-04-18 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0034_latestentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestentry',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
