# Generated by Django 4.2.20 on 2025-07-07 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaqc', '0003_healthcheck'),
        ('monitors', '0034_delete_defaultsensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='current_health',
        ),
        migrations.AddField(
            model_name='monitor',
            name='health',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qaqc.healthcheck'),
        ),
    ]
