# Generated by Django 5.2.16 on 2026-09-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0036_host_monitor_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='county',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
