# Generated by Django 5.2.15 on 2026-07-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0038_pipelinebackfilljob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrybackfilljob',
            name='chunk_days',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='chunk days'),
        ),
        migrations.AlterField(
            model_name='pipelinebackfilljob',
            name='chunk_days',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='chunk days'),
        ),
    ]
