# Generated by Django 4.2.20 on 2025-06-16 13:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalEnviro',
            fields=[
                ('OBJECTID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('tract', models.FloatField(max_length=30, null=True)),
                ('ACS2019Tot', models.FloatField(max_length=20, null=True)),
                ('CIscore', models.FloatField(max_length=20, null=True)),
                ('CIscoreP', models.FloatField(max_length=20, null=True)),
                ('ozone', models.FloatField(max_length=20, null=True)),
                ('ozoneP', models.FloatField(max_length=20, null=True)),
                ('pm', models.FloatField(max_length=20, null=True)),
                ('pmP', models.FloatField(max_length=20, null=True)),
                ('diesel', models.FloatField(max_length=20, null=True)),
                ('dieselP', models.FloatField(max_length=20, null=True)),
                ('pest', models.FloatField(max_length=20, null=True)),
                ('pestP', models.FloatField(max_length=20, null=True)),
                ('RSEIhaz', models.FloatField(max_length=20, null=True)),
                ('RSEIhazP', models.FloatField(max_length=20, null=True)),
                ('asthma', models.FloatField(max_length=20, null=True)),
                ('asthmaP', models.FloatField(max_length=20, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
