# Generated by Django 4.2.20 on 2025-07-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ces4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tract',
            old_name='children_u',
            new_name='children',
        ),
        migrations.RenameField(
            model_name='tract',
            old_name='elderly_65',
            new_name='elderly',
        ),
        migrations.RenameField(
            model_name='tract',
            old_name='pop_10_6_p',
            new_name='pop_10_64_p',
        ),
    ]
