# Generated by Django 4.2.20 on 2025-06-16 15:13

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ces4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calenviro',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='calenviro',
            name='Pollution',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='calenviro',
            name='PollutionP',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='calenviro',
            name='county',
            field=models.CharField(choices=[('fresno', 'Fresno'), ('kern', 'Kern'), ('kings', 'Kings'), ('madera', 'Madera'), ('merced', 'Merced'), ('san joaquin', 'San Joaquin'), ('stanislaus', 'Stanislaus'), ('tulare', 'Tulare')], default=None),
        ),
        migrations.AddField(
            model_name='calenviro',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='calenviro',
            name='cvd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='calenviro',
            name='cvdP',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='calenviro',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='ACS2019Tot',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='CIscore',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='CIscoreP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='RSEIhaz',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='RSEIhazP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='asthma',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='asthmaP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='diesel',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='dieselP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='ozone',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='ozoneP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='pest',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='pestP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='pm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='pmP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calenviro',
            name='tract',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
