# Generated by Django 4.2.22 on 2025-08-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_remove_boundary_record'),
        ('ces4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='boundary',
            field=models.OneToOneField(blank=True, help_text='Boundary object for this given tract.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_boundary', to='regions.boundary'),
        ),
    ]
