# Generated by Django 4.2.20 on 2025-06-16 19:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ces4', '0002_remove_calenviro_timestamp_calenviro_pollution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ces4',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('OBJECTID', models.IntegerField(primary_key=True, serialize=False)),
                ('tract', models.CharField(max_length=30, null=True)),
                ('ACS2019Tot', models.FloatField(null=True)),
                ('CIscore', models.FloatField(null=True)),
                ('CIscoreP', models.FloatField(null=True)),
                ('ozone', models.FloatField(null=True)),
                ('ozoneP', models.FloatField(null=True)),
                ('pm', models.FloatField(null=True)),
                ('pmP', models.FloatField(null=True)),
                ('diesel', models.FloatField(null=True)),
                ('dieselP', models.FloatField(null=True)),
                ('pest', models.FloatField(null=True)),
                ('pestP', models.FloatField(null=True)),
                ('RSEIhaz', models.FloatField(null=True)),
                ('RSEIhazP', models.FloatField(null=True)),
                ('asthma', models.FloatField(null=True)),
                ('asthmaP', models.FloatField(null=True)),
                ('cvd', models.FloatField(null=True)),
                ('cvdP', models.FloatField(null=True)),
                ('pollution', models.FloatField(null=True)),
                ('pollutionP', models.FloatField(null=True)),
                ('county', models.CharField(choices=[('fresno', 'Fresno'), ('kern', 'Kern'), ('kings', 'Kings'), ('madera', 'Madera'), ('merced', 'Merced'), ('san joaquin', 'San Joaquin'), ('stanislaus', 'Stanislaus'), ('tulare', 'Tulare')], default=None)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CalEnviro',
        ),
    ]
