# Generated by Django 4.2.20 on 2025-06-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ces4', '0003_ces4_delete_calenviro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ces4',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ces4',
            name='modified',
        ),
    ]
