# Generated by Django 4.2.20 on 2025-06-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ces4', '0005_ces4_popchar_ces4_popcharp_ces4_popcharsco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ces4',
            old_name='PopChar',
            new_name='popchar',
        ),
        migrations.RenameField(
            model_name='ces4',
            old_name='PopCharP',
            new_name='popcharP',
        ),
        migrations.RenameField(
            model_name='ces4',
            old_name='PopCharSco',
            new_name='popcharS',
        ),
        migrations.AddField(
            model_name='ces4',
            name='pollutionS',
            field=models.FloatField(null=True),
        ),
    ]
