# Generated by Django 4.2.20 on 2025-06-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ces4', '0006_rename_popchar_ces4_pollutions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ces4',
            old_name='popcharS',
            new_name='popcharSco',
        ),
    ]
