# Generated by Django 4.2.14 on 2025-05-14 16:09

import camp.utils.fields.mac_addr
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_smalluuid.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0033_latestentry_defaultsensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True, max_length=100)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirGradient',
            fields=[
                ('monitor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitors.monitor')),
                ('location_id', models.IntegerField(unique=True)),
                ('serial', camp.utils.fields.mac_addr.MACAddressField(max_length=17, validators=[camp.utils.fields.mac_addr.validate_macaddr, camp.utils.fields.mac_addr.validate_macaddr])),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitors', to='airgradient.place')),
            ],
            bases=('monitors.monitor',),
        ),
    ]
