# Generated by Django 4.2.20 on 2025-07-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airgradient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airgradient',
            options={'verbose_name': 'AirGradient'},
        ),
    ]
