# Generated by Django 4.2.22 on 2025-10-14 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airgradient', '0002_alter_airgradient_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airgradient',
            old_name='serial',
            new_name='mac',
        ),
        migrations.RenameField(
            model_name='airgradient',
            old_name='location_id',
            new_name='sensor_id',
        ),
    ]
