# Generated by Django 4.2.22 on 2025-10-20 02:40

import camp.utils.fields.mac_addr
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airgradient', '0002_alter_airgradient_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airgradient',
            old_name='location_id',
            new_name='sensor_id',
        ),
        migrations.RenameField(
            model_name='airgradient',
            old_name='serial',
            new_name='hardware_id',
        ),
        migrations.AlterField(
            model_name='airgradient',
            name='hardware_id',
            field=camp.utils.fields.mac_addr.MACAddressField(blank=True, null=True),
        ),
    ]
