# Generated by Django 5.2.15 on 2026-07-12 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0005_region_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalHeatScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('score', models.IntegerField(choices=[(0, 'Low'), (1, 'Mild'), (2, 'Moderate'), (3, 'High'), (4, 'Severe')], verbose_name='Score')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('region', models.ForeignKey(limit_choices_to={'type': 'zipcode'}, on_delete=django.db.models.deletion.CASCADE, related_name='heat_scores', to='regions.region', verbose_name='ZIP Code')),
            ],
            options={
                'verbose_name': 'CalHeatScore',
                'verbose_name_plural': 'CalHeatScore Records',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('region', 'date'), name='unique_calheatscore_region_date')],
            },
        ),
    ]
