# Generated by Django 5.2.16 on 2026-09-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='sector',
            field=models.CharField(choices=[('dairies-livestock', 'Dairies & livestock'), ('farms', 'Farms & orchards'), ('crop-processing', 'Crop processing & cotton gins'), ('oil-gas', 'Oil & gas production'), ('mining', 'Mining & quarries'), ('glass', 'Glass manufacturing'), ('cement-minerals', 'Cement, concrete & minerals'), ('refining-fuels', 'Refineries, fuel terminals & pipelines'), ('wineries-beverages', 'Wineries & beverages'), ('food-processing', 'Food processing'), ('chemicals', 'Chemicals & fertilizers'), ('power-plants', 'Power plants'), ('waste-water', 'Waste, water & recycling'), ('telecom', 'Telecommunications'), ('transportation', 'Transportation & warehousing'), ('gas-stations', 'Gas stations'), ('auto-repair', 'Auto body & repair'), ('dry-cleaners', 'Dry cleaners'), ('manufacturing', 'Other manufacturing'), ('hospitals-schools', 'Hospitals & schools'), ('government-military', 'Government & military'), ('commercial', 'Commercial & services'), ('other', 'Other')], db_index=True, default='other', max_length=32, verbose_name='Sector'),
        ),
    ]
