# Generated by Django 5.2.16 on 2026-09-22 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_facility_sector'),
        ('regions', '0008_region_type_air_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('inventory', models.CharField(max_length=32, verbose_name='Inventory')),
                ('source_type', models.CharField(choices=[('stationary', 'Stationary'), ('areawide', 'Areawide'), ('mobile', 'Mobile'), ('natural', 'Natural')], db_index=True, max_length=16, verbose_name='Source type')),
                ('eic', models.CharField(max_length=20, verbose_name='EIC')),
                ('summary_name', models.CharField(blank=True, max_length=128, verbose_name='Summary category')),
                ('source_name', models.CharField(blank=True, max_length=128, verbose_name='Source')),
                ('material_name', models.CharField(blank=True, max_length=128, verbose_name='Material')),
                ('subcategory_name', models.CharField(blank=True, max_length=128, verbose_name='Subcategory')),
                ('tog', models.FloatField(null=True, verbose_name='TOG (tons/day)')),
                ('rog', models.FloatField(null=True, verbose_name='ROG (tons/day)')),
                ('co', models.FloatField(null=True, verbose_name='CO (tons/day)')),
                ('nox', models.FloatField(null=True, verbose_name='NOx (tons/day)')),
                ('sox', models.FloatField(null=True, verbose_name='SOx (tons/day)')),
                ('pm', models.FloatField(null=True, verbose_name='Total PM (tons/day)')),
                ('pm10', models.FloatField(null=True, verbose_name='PM10 (tons/day)')),
                ('pm25', models.FloatField(null=True, verbose_name='PM2.5 (tons/day)')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='regions.region', verbose_name='County')),
            ],
            options={
                'verbose_name_plural': 'county inventories',
                'unique_together': {('county', 'year', 'inventory', 'eic')},
            },
        ),
    ]
