# Generated by Django 5.2.16 on 2026-09-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_countyinventory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emissionsrecord',
            index=models.Index(fields=['year', 'facility'], name='emissions_e_year_6de64f_idx'),
        ),
    ]
