# Generated by Django 5.2.16 on 2026-09-25 05:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_emissionsrecord_year_index'),
        ('regions', '0008_region_type_air_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cadd_id', models.IntegerField(unique=True, verbose_name='CADD ID')),
                ('place_id', models.IntegerField(verbose_name='Place ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('address', models.JSONField(blank=True, default=dict, verbose_name='Address')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Point')),
                ('water_board', models.CharField(blank=True, max_length=8, verbose_name='Regional water board')),
                ('cadd_version', models.CharField(max_length=16, verbose_name='CADD version')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dairies', to='regions.region', verbose_name='County')),
            ],
            options={
                'verbose_name_plural': 'dairies',
            },
        ),
        migrations.CreateModel(
            name='Digester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_year', models.IntegerField(verbose_name='Operational year')),
                ('shutdown_year', models.IntegerField(blank=True, null=True, verbose_name='Shutdown year')),
                ('source', models.CharField(blank=True, max_length=16, verbose_name='Data source')),
                ('dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digesters', to='emissions.dairy', verbose_name='Dairy')),
            ],
        ),
        migrations.CreateModel(
            name='DairyHerd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('milk_cows', models.IntegerField(blank=True, null=True, verbose_name='Milk cows')),
                ('dry_cows', models.IntegerField(blank=True, null=True, verbose_name='Dry cows')),
                ('old_heifers', models.IntegerField(blank=True, null=True, verbose_name='Heifers (older)')),
                ('young_heifers', models.IntegerField(blank=True, null=True, verbose_name='Heifers (younger)')),
                ('old_calves', models.IntegerField(blank=True, null=True, verbose_name='Calves (older)')),
                ('young_calves', models.IntegerField(blank=True, null=True, verbose_name='Calves (younger)')),
                ('beef_cattle', models.IntegerField(blank=True, null=True, verbose_name='Beef cattle')),
                ('milk_cows_ref_code', models.CharField(blank=True, max_length=8, verbose_name='Milk cows reference code')),
                ('non_milking_ref_code', models.CharField(blank=True, max_length=8, verbose_name='Non-milking cattle reference code')),
                ('labeled_as_dairy', models.BooleanField(default=False, verbose_name='Labeled as dairy')),
                ('animal_units', models.FloatField(default=0, verbose_name='Animal units (EPA)')),
                ('dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herds', to='emissions.dairy', verbose_name='Dairy')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'dairy'], name='emissions_d_year_655a38_idx')],
                'unique_together': {('dairy', 'year')},
            },
        ),
    ]
