# Generated by Django 5.2.16 on 2026-09-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0005_dairies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digester',
            name='operational_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Operational year'),
        ),
    ]
