# Generated by Django 5.2.16 on 2026-09-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0005_dairies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionsrecord',
            name='acetaldehyde',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='Acetaldehyde (lbs/yr)'),
        ),
        migrations.AlterField(
            model_name='emissionsrecord',
            name='benzene',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='Benzene (lbs/yr)'),
        ),
        migrations.AlterField(
            model_name='emissionsrecord',
            name='butadiene',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='1,3-Butadiene (lbs/yr)'),
        ),
        migrations.AlterField(
            model_name='emissionsrecord',
            name='carbon_tetrachloride',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='Carbon tetrachloride (lbs/yr)'),
        ),
        migrations.AlterField(
            model_name='emissionsrecord',
            name='chromium_hexavalent',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='Chromium hexavalent (lbs/yr)'),
        ),
        migrations.AlterField(
            model_name='emissionsrecord',
            name='dichlorobenzene',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='para-Dichlorobenzene (lbs/yr)'),
        ),
        migrations.AlterField(
            model_name='emissionsrecord',
            name='formaldehyde',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='Formaldehyde (lbs/yr)'),
        ),
        migrations.AlterField(
            model_name='emissionsrecord',
            name='methylene_chloride',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='Methylene chloride (lbs/yr)'),
        ),
        migrations.AlterField(
            model_name='emissionsrecord',
            name='naphthalene',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='Naphthalene (lbs/yr)'),
        ),
        migrations.AlterField(
            model_name='emissionsrecord',
            name='perchloroethylene',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='Perchloroethylene (lbs/yr)'),
        ),
    ]
