# Generated by Django 5.2.16 on 2026-09-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0006_digester_operational_year_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairy',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='City'),
        ),
    ]
