# Generated by Django 5.2.16 on 2026-09-28 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0006_alter_emissionsrecord_acetaldehyde_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=32, verbose_name='Source')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Imported at')),
                ('data_through', models.DateField(blank=True, null=True, verbose_name='Data through')),
                ('version', models.CharField(blank=True, max_length=64, verbose_name='Version')),
                ('notes', models.JSONField(blank=True, default=dict, verbose_name='Notes')),
            ],
            options={
                'ordering': ['-imported_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ToxicPollutant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carb_id', models.CharField(max_length=12, unique=True, verbose_name='CARB pollutant ID')),
                ('cas_number', models.CharField(blank=True, max_length=16, verbose_name='CAS number')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('kind', models.CharField(choices=[('toxic', 'Toxic air contaminant'), ('precursor', 'Precursor')], db_index=True, default='toxic', max_length=12, verbose_name='Kind')),
                ('iur', models.FloatField(blank=True, null=True, verbose_name='Inhalation unit risk (µg/m³)⁻¹')),
                ('chronic_rel', models.FloatField(blank=True, null=True, verbose_name='Chronic REL (µg/m³)')),
                ('acute_rel', models.FloatField(blank=True, null=True, verbose_name='Acute REL (µg/m³)')),
                ('mwaf', models.FloatField(default=1.0, verbose_name='Molecular weight adjustment factor')),
                ('weighted', models.BooleanField(default=True, verbose_name='Weighted')),
                ('cancer_weight', models.FloatField(default=0.0, verbose_name='Cancer weight per lb')),
                ('chronic_weight', models.FloatField(default=0.0, verbose_name='Chronic hazard weight per lb')),
                ('acute_weight', models.FloatField(default=0.0, verbose_name='Acute hazard weight per lb')),
                ('health_values_date', models.DateField(blank=True, null=True, verbose_name='Health values date')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='emissionsrecord',
            name='ahindex',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Acute hazard index'),
        ),
        migrations.AlterField(
            model_name='emissionsrecord',
            name='chindex',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chronic hazard index'),
        ),
        migrations.CreateModel(
            name='ToxicEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('lbs', models.DecimalField(decimal_places=15, max_digits=25, verbose_name='Emissions (lbs/yr)')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toxic_emissions', to='emissions.facility', verbose_name='Facility')),
                ('pollutant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emissions', to='emissions.toxicpollutant', verbose_name='Pollutant')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'pollutant'], name='emissions_t_year_11c837_idx'), models.Index(fields=['pollutant', 'year'], name='emissions_t_polluta_6e9f9a_idx')],
                'unique_together': {('facility', 'year', 'pollutant')},
            },
        ),
    ]
