# Generated by Django 5.2.16 on 2026-09-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0008_copy_named_toxics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionsrecord',
            name='acetaldehyde',
        ),
        migrations.RemoveField(
            model_name='emissionsrecord',
            name='benzene',
        ),
        migrations.RemoveField(
            model_name='emissionsrecord',
            name='butadiene',
        ),
        migrations.RemoveField(
            model_name='emissionsrecord',
            name='carbon_tetrachloride',
        ),
        migrations.RemoveField(
            model_name='emissionsrecord',
            name='chromium_hexavalent',
        ),
        migrations.RemoveField(
            model_name='emissionsrecord',
            name='dichlorobenzene',
        ),
        migrations.RemoveField(
            model_name='emissionsrecord',
            name='formaldehyde',
        ),
        migrations.RemoveField(
            model_name='emissionsrecord',
            name='methylene_chloride',
        ),
        migrations.RemoveField(
            model_name='emissionsrecord',
            name='naphthalene',
        ),
        migrations.RemoveField(
            model_name='emissionsrecord',
            name='perchloroethylene',
        ),
    ]
