# Generated by Django 5.2.16 on 2026-09-29 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0010_facility_point_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirComplianceFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgm_sys_id', models.CharField(max_length=20, unique=True, verbose_name='ICIS-Air id')),
                ('registry_id', models.CharField(blank=True, max_length=12, verbose_name='FRS registry id')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('address', models.JSONField(blank=True, default=dict, verbose_name='Address')),
                ('pollutant_class', models.CharField(blank=True, max_length=32, verbose_name='Pollutant class')),
                ('operating_status', models.CharField(blank=True, max_length=40, verbose_name='Operating status')),
                ('title_v', models.BooleanField(default=False, verbose_name='Title V')),
                ('current_hpv', models.CharField(blank=True, max_length=40, verbose_name='Current HPV status')),
                ('local_region', models.CharField(blank=True, max_length=8, verbose_name='Local control region')),
                ('match_method', models.CharField(blank=True, choices=[('parsed', 'Parsed from the ICIS id'), ('manual', 'Hand-kept crosswalk')], max_length=8, verbose_name='Match method')),
                ('reported_through', models.DateField(blank=True, null=True, verbose_name='Reported through')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icis_facilities', to='emissions.facility', verbose_name='Facility')),
            ],
            options={
                'verbose_name_plural': 'air compliance facilities',
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('inspection', 'Inspection'), ('nov', 'Notice of violation'), ('formal', 'Formal action'), ('hpv', 'High-priority violation')], max_length=12, verbose_name='Kind')),
                ('date', models.DateField(verbose_name='Date')),
                ('agency', models.CharField(blank=True, choices=[('L', 'Air district'), ('S', 'State'), ('E', 'EPA')], max_length=1, verbose_name='Agency')),
                ('action_type', models.CharField(blank=True, max_length=80, verbose_name='Action type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Penalty')),
                ('program', models.CharField(blank=True, max_length=40, verbose_name='Program')),
                ('pollutant', models.CharField(blank=True, max_length=40, verbose_name='Pollutant')),
                ('resolved', models.DateField(blank=True, null=True, verbose_name='Resolved')),
                ('external_id', models.CharField(max_length=40, verbose_name='ICIS activity id')),
                ('icis_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='emissions.aircompliancefacility', verbose_name='ICIS facility')),
            ],
            options={
                'indexes': [models.Index(fields=['icis_facility', 'kind', 'date'], name='emissions_c_icis_fa_618401_idx')],
                'unique_together': {('icis_facility', 'kind', 'external_id')},
            },
        ),
    ]
