# Generated by Django 5.2.16 on 2026-09-29 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0011_compliance'),
        ('regions', '0010_remove_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyNEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='NEI year')),
                ('pollutant', models.CharField(default='NH3', max_length=8, verbose_name='Pollutant code')),
                ('sector', models.CharField(max_length=128, verbose_name='EPA sector')),
                ('subsector', models.CharField(blank=True, max_length=128, verbose_name='Subsector')),
                ('tons', models.FloatField(verbose_name='Emissions (tons/yr)')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='regions.region', verbose_name='County')),
            ],
            options={
                'verbose_name': 'county NEI row',
                'verbose_name_plural': 'county NEI rows',
                'unique_together': {('county', 'year', 'pollutant', 'sector', 'subsector')},
            },
        ),
    ]
