# Generated by Django 5.2.16 on 2026-09-29 07:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0012_countynei'),
        ('regions', '0010_remove_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=14, unique=True, verbose_name='API number')),
                ('lease_name', models.CharField(blank=True, max_length=128, verbose_name='Lease')),
                ('well_number', models.CharField(blank=True, max_length=32, verbose_name='Well number')),
                ('designation', models.CharField(blank=True, max_length=64, verbose_name='Designation')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Idle', 'Idle'), ('New', 'New')], db_index=True, max_length=8, verbose_name='Status')),
                ('well_type', models.CharField(blank=True, max_length=8, verbose_name='Well type code')),
                ('well_type_label', models.CharField(blank=True, max_length=64, verbose_name='Well type')),
                ('operator_code', models.CharField(blank=True, max_length=16, verbose_name='Operator code')),
                ('operator_name', models.CharField(blank=True, max_length=128, verbose_name='Operator')),
                ('field_name', models.CharField(blank=True, max_length=128, verbose_name='Field')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Point')),
                ('spud_date', models.DateField(blank=True, null=True, verbose_name='Spud date')),
                ('in_hpz', models.CharField(blank=True, choices=[('Verified HPZ', 'Verified health protection zone'), ('Uncertainty Area', 'Uncertainty area'), ('Not Within HPZ', 'Not within a health protection zone')], max_length=24, verbose_name='Health protection zone')),
                ('directional', models.BooleanField(default=False, verbose_name='Directionally drilled')),
                ('imported_at', models.DateTimeField(auto_now=True, verbose_name='Imported at')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wells', to='regions.region', verbose_name='County')),
            ],
            options={
                'ordering': ['api'],
                'indexes': [models.Index(fields=['county', 'status'], name='emissions_w_county__bb389b_idx')],
            },
        ),
    ]
