# Generated by Django 5.2.16 on 2026-09-29 08:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0013_well'),
        ('regions', '0010_remove_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHGReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('ghgrp', 'EPA GHGRP'), ('mrr', 'CARB MRR')], db_index=True, max_length=8, verbose_name='Program')),
                ('external_id', models.CharField(max_length=20, verbose_name='External id')),
                ('year', models.IntegerField(db_index=True, verbose_name='Year')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='City')),
                ('zipcode', models.CharField(blank=True, max_length=10, verbose_name='ZIP code')),
                ('naics', models.CharField(blank=True, max_length=8, verbose_name='NAICS')),
                ('sector', models.CharField(blank=True, max_length=128, verbose_name='Sector')),
                ('subparts', models.CharField(blank=True, max_length=128, verbose_name='Subparts')),
                ('co2e', models.FloatField(verbose_name='CO2e (metric tons)')),
                ('co2e_biogenic', models.FloatField(blank=True, null=True, verbose_name='Biogenic CO2 (metric tons)')),
                ('ch4', models.FloatField(blank=True, null=True, verbose_name='CH4 (metric tons)')),
                ('n2o', models.FloatField(blank=True, null=True, verbose_name='N2O (metric tons)')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point')),
                ('frs_id', models.CharField(blank=True, max_length=12, verbose_name='FRS registry id')),
                ('basin_wide', models.BooleanField(default=False, verbose_name='Basin-wide')),
                ('match_method', models.CharField(blank=True, choices=[('frs', 'FRS air program id'), ('crosswalk', 'Hand-curated crosswalk'), ('auto', 'Name and place'), ('', 'Unmatched')], default='', max_length=10, verbose_name='Match method')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='regions.region', verbose_name='County')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghg_reports', to='emissions.facility', verbose_name='Facility')),
            ],
            options={
                'verbose_name': 'GHG report',
                'ordering': ['-co2e'],
                'unique_together': {('program', 'external_id', 'year')},
            },
        ),
    ]
