# Generated by Django 5.2.16 on 2026-09-29 16:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0014_ghgreport'),
        ('regions', '0010_remove_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethaneSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=64, unique=True, verbose_name='Source name')),
                ('gas', models.CharField(choices=[('CH4', 'Methane'), ('CO2', 'Carbon dioxide')], db_index=True, max_length=3, verbose_name='Gas')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Point')),
                ('ipcc_sector', models.CharField(blank=True, max_length=8, verbose_name='IPCC sector')),
                ('sector_label', models.CharField(blank=True, max_length=32, verbose_name='Sector')),
                ('persistence', models.FloatField(blank=True, null=True, verbose_name='Persistence')),
                ('emission_kg_h', models.FloatField(blank=True, null=True, verbose_name='Emission rate (kg/h)')),
                ('uncertainty_kg_h', models.FloatField(blank=True, null=True, verbose_name='Emission uncertainty (kg/h)')),
                ('observations', models.IntegerField(default=0, verbose_name='Observation dates')),
                ('detections', models.IntegerField(default=0, verbose_name='Detection dates')),
                ('distance_m', models.FloatField(blank=True, null=True, verbose_name='Distance to the match (m)')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Fetched at')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='methane_sources', to='regions.region', verbose_name='County')),
                ('dairy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='methane_sources', to='emissions.dairy', verbose_name='Nearest dairy')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='methane_sources', to='emissions.facility', verbose_name='Nearest facility')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('emission_kg_h'), descending=True, nulls_last=True), 'source_name'],
                'indexes': [models.Index(fields=['county', 'gas'], name='emissions_m_county__eb4f70_idx')],
            },
        ),
    ]
