# Generated by Django 5.2.16 on 2026-09-29 18:20

import camp.apps.emissions.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0015_methanesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethanePlume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plume_id', models.CharField(max_length=64, unique=True, verbose_name='Plume id')),
                ('observed_at', models.DateTimeField(verbose_name='Observed at')),
                ('platform', models.CharField(blank=True, max_length=32, verbose_name='Platform')),
                ('instrument', models.CharField(blank=True, max_length=16, verbose_name='Instrument')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Point')),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Bounds')),
                ('emission_kg_h', models.FloatField(blank=True, null=True, verbose_name='Emission rate (kg/h)')),
                ('uncertainty_kg_h', models.FloatField(blank=True, null=True, verbose_name='Emission uncertainty (kg/h)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Wind speed')),
                ('wind_direction', models.FloatField(blank=True, null=True, verbose_name='Wind direction')),
                ('image', models.ImageField(blank=True, upload_to=camp.apps.emissions.models.methane_plume_upload_to, verbose_name='Plume image')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Fetched at')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plumes', to='emissions.methanesource', verbose_name='Source')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['source', '-observed_at'], name='emissions_m_source__801d2f_idx')],
            },
        ),
    ]
