# Generated by Django 5.2.16 on 2026-09-29 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0016_methaneplume'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigesterGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128, verbose_name='Project')),
                ('dairy_name', models.CharField(max_length=128, verbose_name='Dairy name')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='City')),
                ('county', models.CharField(blank=True, max_length=32, verbose_name='County')),
                ('developer', models.CharField(blank=True, max_length=128, verbose_name='Developer')),
                ('grant_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Grant amount')),
                ('end_use', models.CharField(blank=True, max_length=64, verbose_name='Biogas end use')),
                ('est_reduction_tco2e', models.FloatField(blank=True, null=True, verbose_name='Estimated reduction (t CO2e/yr)')),
                ('awarded', models.DateField(blank=True, null=True, verbose_name='Awarded')),
                ('operational', models.DateField(blank=True, null=True, verbose_name='Operational')),
                ('match_method', models.CharField(blank=True, choices=[('auto', 'Name and city'), ('manual', 'Crosswalk')], max_length=8, verbose_name='Match method')),
                ('dairy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='emissions.dairy', verbose_name='Dairy')),
            ],
            options={
                'ordering': ['-awarded', 'dairy_name'],
            },
        ),
    ]
