# Generated by Django 5.2.16 on 2026-10-03 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0017_digestergrant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methanesource',
            name='dairy',
        ),
        migrations.RemoveField(
            model_name='methanesource',
            name='distance_m',
        ),
        migrations.RemoveField(
            model_name='methanesource',
            name='facility',
        ),
    ]
