# Generated by Django 5.2.15 on 2026-07-12 01:48

from django.contrib.postgres.operations import CreateExtension
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis_raster'),
        migrations.CreateModel(
            name='Granule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('no2', 'Nitrogen Dioxide'), ('o3tot', 'Total Ozone'), ('hcho', 'Formaldehyde'), ('cldo4', 'Cloud Fraction')], max_length=10, verbose_name='product')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('version', models.CharField(max_length=10, verbose_name='version')),
                ('is_final', models.BooleanField(default=False, verbose_name='is final')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326, verbose_name='raster')),
                ('preview', models.ImageField(upload_to='tempo/previews/', verbose_name='preview')),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='bounds')),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['product', 'timestamp'], name='tempo_granu_product_174145_idx')],
                'unique_together': {('product', 'timestamp')},
            },
        ),
    ]
