# Generated by Django 5.2.15 on 2026-07-13 02:52

import camp.apps.tempo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granule',
            name='preview',
            field=models.ImageField(upload_to=camp.apps.tempo.models.granule_preview_upload_to, verbose_name='preview'),
        ),
    ]
