# Generated by Django 4.2.20 on 2025-07-31 16:36

import camp.apps.integrate.tempo.models
from django.db import migrations, models
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempoGrid',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('pollutant', models.CharField(choices=[('o3tot', 'Ozone'), ('hcho', 'Formaldehyde'), ('no2', 'Nitrogen Dioxide')], max_length=5)),
                ('timestamp', models.DateTimeField(null=True)),
                ('timestamp_2', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=camp.apps.integrate.tempo.models.file_path)),
                ('final', models.BooleanField()),
            ],
        ),
    ]
