# Generated by Django 4.2.20 on 2025-06-26 18:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollutantPoint',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('amount', models.FloatField()),
                ('pollutant', models.CharField(choices=[('o3tot', 'O3Tot'), ('no2', 'NO2'), ('hcho', 'HCHO')], max_length=5)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
