# Generated by Django 4.2.20 on 2025-07-24 15:51

from django.db import migrations, models
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HchoFile',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('file', models.FileField(null=True, upload_to='observations/hcho/')),
            ],
        ),
        migrations.CreateModel(
            name='No2File',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('file', models.FileField(null=True, upload_to='observations/no2/')),
            ],
        ),
        migrations.CreateModel(
            name='O3totFile',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('file', models.FileField(null=True, upload_to='observations/o3tot/')),
            ],
        ),
    ]
