# Generated by Django 4.2.20 on 2025-07-01 17:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCHO_Points',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('amount', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='NO2_Points',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('amount', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='O3TOT_Points',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('amount', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='PollutantPoint',
        ),
    ]
