# Generated by Django 4.2.20 on 2025-07-25 16:57

import camp.apps.integrate.tempo.models
from django.db import migrations, models
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempoGrid',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(db_index=True, default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('pollutant', models.CharField(choices=[('o3tot', 'Ozone'), ('hcho', 'Formaldehyde'), ('no2', 'Nitrogen Dioxide')], max_length=5)),
                ('timestamp', models.DateTimeField(null=True)),
                ('shp', models.FileField(blank=True, null=True, upload_to=camp.apps.integrate.tempo.models.file_path)),
                ('dbf', models.FileField(blank=True, null=True, upload_to=camp.apps.integrate.tempo.models.file_path)),
                ('prj', models.FileField(blank=True, null=True, upload_to=camp.apps.integrate.tempo.models.file_path)),
                ('cpg', models.FileField(blank=True, null=True, upload_to=camp.apps.integrate.tempo.models.file_path)),
                ('shx', models.FileField(blank=True, null=True, upload_to=camp.apps.integrate.tempo.models.file_path)),
            ],
        ),
        migrations.DeleteModel(
            name='HchoFile',
        ),
        migrations.DeleteModel(
            name='No2File',
        ),
        migrations.DeleteModel(
            name='O3totFile',
        ),
    ]
