# Generated by Django 4.2.20 on 2025-07-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0002_tempogrid_delete_hchofile_delete_no2file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempogrid',
            name='timestamp_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
