# Generated by Django 4.2.20 on 2025-07-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0002_hcho_points_no2_points_o3tot_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hcho_points',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='hcho_points',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='no2_points',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='no2_points',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='o3tot_points',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='o3tot_points',
            name='geometry',
        ),
        migrations.AddField(
            model_name='hcho_points',
            name='file',
            field=models.FileField(null=True, upload_to='observations/HCHO/'),
        ),
        migrations.AddField(
            model_name='no2_points',
            name='file',
            field=models.FileField(null=True, upload_to='observations/NO2/'),
        ),
        migrations.AddField(
            model_name='o3tot_points',
            name='file',
            field=models.FileField(null=True, upload_to='observations/O3TOT/'),
        ),
    ]
