# Generated by Django 4.2.20 on 2025-07-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0003_tempogrid_timestamp_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempogrid',
            name='final',
            field=models.BooleanField(default=True),
        ),
    ]
