# Generated by Django 4.2.20 on 2025-07-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0003_remove_hcho_points_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HCHO_Points',
            new_name='HchoFile',
        ),
        migrations.RenameModel(
            old_name='NO2_Points',
            new_name='No2File',
        ),
        migrations.RenameModel(
            old_name='O3TOT_Points',
            new_name='O3totFile',
        ),
    ]
