# Generated by Django 4.2.29 on 2026-03-20 23:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                ("modified", model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified")),
                ("county_code", models.IntegerField(verbose_name="County code")),
                ("facid", models.IntegerField(verbose_name="Facility ID")),
                ("metadata_year", models.IntegerField(blank=True, null=True, verbose_name="Metadata year")),
                ("name", models.CharField(max_length=60, verbose_name="Name")),
                ("sic_code", models.IntegerField(blank=True, null=True, verbose_name="SIC code")),
                ("address", models.JSONField(blank=True, default=dict, verbose_name="Address")),
                ("point", django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name="Point")),
                ("city", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="city_facilities", to="regions.region", verbose_name="City")),
                ("county", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="county_facilities", to="regions.region", verbose_name="County")),
                ("zipcode", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="zipcode_facilities", to="regions.region", verbose_name="Zipcode")),
            ],
            options={
                "unique_together": {("county_code", "facid")},
            },
        ),
        migrations.CreateModel(
            name="EmissionsRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name="created")),
                ("modified", model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name="modified")),
                ("year", models.IntegerField(verbose_name="Year")),
                ("tog", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="TOG")),
                ("rog", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="ROG")),
                ("co", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="CO")),
                ("nox", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="NOx")),
                ("sox", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="SOx")),
                ("pm25", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="PM2.5")),
                ("pm10", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="PM10")),
                ("total_score", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Total score")),
                ("hra", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="HRA")),
                ("chindex", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Cancer health index")),
                ("ahindex", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Acute health index")),
                ("acetaldehyde", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="Acetaldehyde")),
                ("benzene", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="Benzene")),
                ("butadiene", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="1,3-Butadiene")),
                ("carbon_tetrachloride", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="Carbon tetrachloride")),
                ("chromium_hexavalent", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="Chromium (hexavalent)")),
                ("dichlorobenzene", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="para-Dichlorobenzene")),
                ("formaldehyde", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="Formaldehyde")),
                ("methylene_chloride", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="Methylene chloride")),
                ("naphthalene", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="Naphthalene")),
                ("perchloroethylene", models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name="Perchloroethylene")),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="emissions", to="ceidars.facility")),
            ],
            options={
                "unique_together": {("facility", "year")},
            },
        ),
    ]
