# Generated by Django 4.2.29 on 2026-03-20 04:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('county_code', models.IntegerField()),
                ('facid', models.IntegerField()),
                ('metadata_year', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=60)),
                ('sic_code', models.IntegerField(blank=True, null=True)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_facilities', to='regions.region')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_facilities', to='regions.region')),
                ('zipcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zipcode_facilities', to='regions.region')),
            ],
            options={
                'unique_together': {('county_code', 'facid')},
            },
        ),
        migrations.CreateModel(
            name='EmissionsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('year', models.IntegerField()),
                ('tog', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('rog', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('co', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('nox', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('sox', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('pm25', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('pm10', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chindex', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ahindex', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='ceidars.facility')),
            ],
            options={
                'unique_together': {('facility', 'year')},
            },
        ),
    ]
