# Generated by Django 4.2.30 on 2026-06-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_smoke', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Smoke',
        ),
    ]
