# Generated by Django 4.2.20 on 2025-06-11 13:25

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hms_smoke', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smoke',
            name='FID',
        ),
        migrations.RemoveField(
            model_name='smoke',
            name='observation_time',
        ),
        migrations.AddField(
            model_name='smoke',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='smoke',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='density',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='light', max_length=10),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='satellite',
            field=models.CharField(max_length=20),
        ),
    ]
