# Generated by Django 4.2.20 on 2025-06-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_smoke', '0002_remove_smoke_fid_remove_smoke_observation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smoke',
            name='created',
        ),
        migrations.RemoveField(
            model_name='smoke',
            name='modified',
        ),
        migrations.AddField(
            model_name='smoke',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
