# Generated by Django 4.2.20 on 2025-07-03 19:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_smoke', '0003_remove_smoke_created_remove_smoke_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smoke',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='smoke',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='smoke',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='start',
            field=models.TimeField(null=True),
        ),
    ]
