# Generated by Django 4.2.20 on 2025-07-03 19:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_smoke', '0004_remove_smoke_timestamp_smoke_date_smoke_is_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoke',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
