# Generated by Django 4.2.4 on 2023-09-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaqc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensoranalysis',
            name='grade',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sensoranalysis',
            name='variance',
            field=models.FloatField(default=None, null=True),
        ),
    ]
