# Generated by Django 4.2.4 on 2023-08-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0026_entry_ozone'),
        ('qaqc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensoranalysis',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_analysis', to='monitors.monitor'),
        ),
    ]
