# Generated by Django 4.2.4 on 2023-08-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qaqc', '0002_alter_sensoranalysis_monitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorAnalysis',
        ),
    ]
