# Generated by Django 4.2.20 on 2025-07-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0035_remove_monitor_current_health_monitor_health'),
        ('qaqc', '0003_healthcheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcheck',
            options={'ordering': ['-hour', 'monitor']},
        ),
        migrations.DeleteModel(
            name='SensorAnalysis',
        ),
    ]
