# Generated by Django 4.2.20 on 2025-07-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaqc', '0004_alter_healthcheck_options_delete_sensoranalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheck',
            name='variance',
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='count_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='count_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='flatline_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='flatline_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='mad_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='mad_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='max_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='max_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='mean_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='mean_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='min_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='min_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='range_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='range_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='rmse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='rpd_means',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='rpd_pairwise',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='stdev_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='stdev_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='variance_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='variance_b',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
