# Generated by Django 4.2.20 on 2025-07-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaqc', '0005_remove_healthcheck_variance_healthcheck_count_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='sanity_completeness_a',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='sanity_completeness_b',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='sanity_flatline_a',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='sanity_flatline_b',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='sanity_max_a',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='sanity_max_b',
            field=models.BooleanField(null=True),
        ),
    ]
